-- 1000 mots néerlandais de base pour Knowledge Quiz
-- Exécuter dans Supabase SQL Editor après avoir ajouté la colonne is_system:
-- ALTER TABLE public.vocabulary ADD COLUMN IF NOT EXISTS is_system boolean DEFAULT false;

INSERT INTO vocabulary (source_word, target_translation, language_pair, example_sentence, is_system) VALUES

-- Numbers/math (25)
('één', 'un', 'nl-fr', 'Ik heb één broer.', true),
('twee', 'deux', 'nl-fr', 'Er zijn twee katten in de tuin.', true),
('drie', 'trois', 'nl-fr', 'We eten om drie uur.', true),
('vier', 'quatre', 'nl-fr', 'Het gezin heeft vier kinderen.', true),
('vijf', 'cinq', 'nl-fr', 'Ik werk vijf dagen per week.', true),
('zes', 'six', 'nl-fr', 'De winkel sluit om zes uur.', true),
('zeven', 'sept', 'nl-fr', 'Er zijn zeven dagen in een week.', true),
('acht', 'huit', 'nl-fr', 'De trein vertrekt om acht uur.', true),
('negen', 'neuf', 'nl-fr', 'Hij is negen jaar oud.', true),
('tien', 'dix', 'nl-fr', 'Tien minuten lopen van hier.', true),
('elf', 'onze', 'nl-fr', 'Het zijn elf spelers in een voetbalteam.', true),
('twaalf', 'douze', 'nl-fr', 'Er zijn twaalf maanden in een jaar.', true),
('twintig', 'vingt', 'nl-fr', 'Hij heeft twintig euro betaald.', true),
('dertig', 'trente', 'nl-fr', 'Ze woont dertig kilometer ver.', true),
('veertig', 'quarante', 'nl-fr', 'Hij is veertig jaar oud.', true),
('vijftig', 'cinquante', 'nl-fr', 'De fiets kost vijftig euro.', true),
('honderd', 'cent', 'nl-fr', 'Er waren honderd mensen aanwezig.', true),
('duizend', 'mille', 'nl-fr', 'Duizend mensen bezochten het museum.', true),
('nul', 'zéro', 'nl-fr', 'De temperatuur is nul graden.', true),
('eerste', 'premier', 'nl-fr', 'Zij is de eerste in de klas.', true),
('tweede', 'deuxième', 'nl-fr', 'Hij woont op de tweede verdieping.', true),
('half', 'demi', 'nl-fr', 'We vertrekken om half drie.', true),
('kwart', 'quart', 'nl-fr', 'Het is kwart over vier.', true),
('het getal', 'le chiffre', 'nl-fr', 'Dit getal is erg groot.', true),
('het miljoen', 'le million', 'nl-fr', 'Een miljoen mensen wonen in deze stad.', true),

-- Days (7)
('maandag', 'lundi', 'nl-fr', 'Op maandag ga ik naar het werk.', true),
('dinsdag', 'mardi', 'nl-fr', 'Dinsdag hebben we een vergadering.', true),
('woensdag', 'mercredi', 'nl-fr', 'Woensdag is het midden van de week.', true),
('donderdag', 'jeudi', 'nl-fr', 'Op donderdag ga ik sporten.', true),
('vrijdag', 'vendredi', 'nl-fr', 'Vrijdag is mijn favoriete dag.', true),
('zaterdag', 'samedi', 'nl-fr', 'Op zaterdag slaap ik lang.', true),
('zondag', 'dimanche', 'nl-fr', 'Zondag eten we samen als familie.', true),

-- Months (12)
('januari', 'janvier', 'nl-fr', 'In januari is het erg koud.', true),
('februari', 'février', 'nl-fr', 'Februari is de kortste maand.', true),
('maart', 'mars', 'nl-fr', 'In maart begint de lente.', true),
('april', 'avril', 'nl-fr', 'Het regent veel in april.', true),
('mei', 'mai', 'nl-fr', 'De bloemen bloeien in mei.', true),
('juni', 'juin', 'nl-fr', 'Juni is een warme maand.', true),
('juli', 'juillet', 'nl-fr', 'In juli gaan we op vakantie.', true),
('augustus', 'août', 'nl-fr', 'Augustus is de warmste maand.', true),
('september', 'septembre', 'nl-fr', 'School begint in september.', true),
('oktober', 'octobre', 'nl-fr', 'In oktober vallen de bladeren.', true),
('november', 'novembre', 'nl-fr', 'November is een grijze maand.', true),
('december', 'décembre', 'nl-fr', 'In december vieren we Kerstmis.', true),

-- Time (12)
('de dag', 'le jour', 'nl-fr', 'De dag begint vroeg in de ochtend.', true),
('de week', 'la semaine', 'nl-fr', 'Deze week is erg druk.', true),
('de maand', 'le mois', 'nl-fr', 'De maand januari is koud.', true),
('het jaar', 'l''année', 'nl-fr', 'Dit jaar gaan we naar Parijs.', true),
('het uur', 'l''heure', 'nl-fr', 'Het uur gaat snel voorbij.', true),
('de minuut', 'la minute', 'nl-fr', 'Wacht een minuut, alsjeblieft.', true),
('de seconde', 'la seconde', 'nl-fr', 'Een seconde kan veel veranderen.', true),
('de ochtend', 'le matin', 'nl-fr', 'In de ochtend drink ik koffie.', true),
('de middag', 'le midi', 'nl-fr', 'Om de middag eet ik een boterham.', true),
('de avond', 'le soir', 'nl-fr', 'In de avond kijk ik televisie.', true),
('de nacht', 'la nuit', 'nl-fr', 'De nacht is lang en donker.', true),
('gisteren', 'hier', 'nl-fr', 'Gisteren was het mooi weer.', true),

-- Seasons/weather (20)
('de lente', 'le printemps', 'nl-fr', 'In de lente bloeien de bloemen.', true),
('de zomer', 'l''été', 'nl-fr', 'In de zomer gaan we zwemmen.', true),
('de herfst', 'l''automne', 'nl-fr', 'In de herfst vallen de bladeren.', true),
('de winter', 'l''hiver', 'nl-fr', 'In de winter sneeuwt het soms.', true),
('de regen', 'la pluie', 'nl-fr', 'De regen valt de hele dag.', true),
('de zon', 'le soleil', 'nl-fr', 'De zon schijnt vandaag.', true),
('de wind', 'le vent', 'nl-fr', 'De wind waait hard vandaag.', true),
('de sneeuw', 'la neige', 'nl-fr', 'De sneeuw maakt alles wit.', true),
('de wolk', 'le nuage', 'nl-fr', 'Er zijn veel wolken in de lucht.', true),
('het onweer', 'l''orage', 'nl-fr', 'Het onweer is erg hevig.', true),
('de mist', 'le brouillard', 'nl-fr', 'De mist maakt rijden gevaarlijk.', true),
('de storm', 'la tempête', 'nl-fr', 'De storm heeft bomen omgegooid.', true),
('de bliksem', 'l''éclair', 'nl-fr', 'De bliksem verlicht de lucht.', true),
('de donder', 'le tonnerre', 'nl-fr', 'De donder klinkt heel luid.', true),
('de hagel', 'la grêle', 'nl-fr', 'De hagel beschadigt de auto.', true),
('de temperatuur', 'la température', 'nl-fr', 'De temperatuur stijgt in de zomer.', true),
('het weerbericht', 'le bulletin météo', 'nl-fr', 'Het weerbericht voorspelt regen.', true),
('de lucht', 'le ciel', 'nl-fr', 'De lucht is blauw vandaag.', true),
('het ijzel', 'le verglas', 'nl-fr', 'Door het ijzel is de weg gevaarlijk.', true),
('de droogte', 'la sécheresse', 'nl-fr', 'De droogte schaadt de gewassen.', true),

-- Colors (15)
('rood', 'rouge', 'nl-fr', 'De roos is rood.', true),
('blauw', 'bleu', 'nl-fr', 'De lucht is blauw.', true),
('groen', 'vert', 'nl-fr', 'Het gras is groen.', true),
('geel', 'jaune', 'nl-fr', 'De zon is geel.', true),
('zwart', 'noir', 'nl-fr', 'De nacht is zwart.', true),
('wit', 'blanc', 'nl-fr', 'Sneeuw is wit.', true),
('grijs', 'gris', 'nl-fr', 'De lucht is grijs vandaag.', true),
('oranje', 'orange', 'nl-fr', 'De sinaasappel is oranje.', true),
('roze', 'rose', 'nl-fr', 'Haar jurk is roze.', true),
('paars', 'violet', 'nl-fr', 'De bloem is paars.', true),
('bruin', 'brun', 'nl-fr', 'De chocolade is bruin.', true),
('beige', 'beige', 'nl-fr', 'De muur is beige geschilderd.', true),
('goud', 'or', 'nl-fr', 'De ring is van goud.', true),
('zilver', 'argent', 'nl-fr', 'De ketting is van zilver.', true),
('de kleur', 'la couleur', 'nl-fr', 'Wat is je favoriete kleur?', true),

-- Body parts (30)
('het hoofd', 'la tête', 'nl-fr', 'Mijn hoofd doet pijn.', true),
('het haar', 'les cheveux', 'nl-fr', 'Haar haar is lang en blond.', true),
('het oog', 'l''œil', 'nl-fr', 'Hij heeft blauwe ogen.', true),
('het oor', 'l''oreille', 'nl-fr', 'Het oor is gevoelig voor harde geluiden.', true),
('de neus', 'le nez', 'nl-fr', 'Mijn neus loopt.', true),
('de mond', 'la bouche', 'nl-fr', 'Open je mond bij de tandarts.', true),
('de tand', 'la dent', 'nl-fr', 'De tand doet pijn.', true),
('de tong', 'la langue', 'nl-fr', 'De tong helpt ons proeven.', true),
('de keel', 'la gorge', 'nl-fr', 'Mijn keel is ontstoken.', true),
('de nek', 'le cou', 'nl-fr', 'Mijn nek is stijf.', true),
('de schouder', 'l''épaule', 'nl-fr', 'Hij heeft pijn in zijn schouder.', true),
('de arm', 'le bras', 'nl-fr', 'Ze draagt een armband om haar arm.', true),
('de elleboog', 'le coude', 'nl-fr', 'Hij heeft zijn elleboog gestoten.', true),
('de hand', 'la main', 'nl-fr', 'Was je handen voor het eten.', true),
('de vinger', 'le doigt', 'nl-fr', 'Hij heeft een ring om zijn vinger.', true),
('de borst', 'la poitrine', 'nl-fr', 'Ze voelt pijn in haar borst.', true),
('de buik', 'le ventre', 'nl-fr', 'Mijn buik doet pijn na het eten.', true),
('de rug', 'le dos', 'nl-fr', 'Hij heeft rugpijn van het tillen.', true),
('het been', 'la jambe', 'nl-fr', 'Ze heeft haar been gebroken.', true),
('de knie', 'le genou', 'nl-fr', 'Mijn knie doet pijn na het sporten.', true),
('de voet', 'le pied', 'nl-fr', 'Mijn voet is gezwollen.', true),
('de teen', 'l''orteil', 'nl-fr', 'Hij heeft zijn teen gestoten.', true),
('de huid', 'la peau', 'nl-fr', 'De huid beschermt het lichaam.', true),
('het hart', 'le cœur', 'nl-fr', 'Het hart pompt bloed door het lichaam.', true),
('de long', 'le poumon', 'nl-fr', 'De long is belangrijk voor ademhalen.', true),
('de maag', 'l''estomac', 'nl-fr', 'Mijn maag knort van de honger.', true),
('de hersenen', 'le cerveau', 'nl-fr', 'De hersenen sturen het lichaam aan.', true),
('het bloed', 'le sang', 'nl-fr', 'Het bloed stroomt door de aderen.', true),
('het bot', 'l''os', 'nl-fr', 'Het bot is gebroken.', true),
('de spier', 'le muscle', 'nl-fr', 'De spier is gespannen na het sporten.', true),

-- Family/people (28)
('de moeder', 'la mère', 'nl-fr', 'Mijn moeder kookt elke avond.', true),
('de vader', 'le père', 'nl-fr', 'Mijn vader werkt hard.', true),
('de broer', 'le frère', 'nl-fr', 'Mijn broer is ouder dan ik.', true),
('de zus', 'la sœur', 'nl-fr', 'Mijn zus woont in Amsterdam.', true),
('de grootmoeder', 'la grand-mère', 'nl-fr', 'Mijn grootmoeder bakt de beste taart.', true),
('de grootvader', 'le grand-père', 'nl-fr', 'Mijn grootvader vertelt verhalen.', true),
('de oom', 'l''oncle', 'nl-fr', 'Mijn oom woont in België.', true),
('de tante', 'la tante', 'nl-fr', 'Mijn tante is erg grappig.', true),
('de neef', 'le cousin', 'nl-fr', 'Mijn neef speelt voetbal.', true),
('de nicht', 'la cousine', 'nl-fr', 'Mijn nicht studeert geneeskunde.', true),
('het kind', 'l''enfant', 'nl-fr', 'Het kind speelt in de tuin.', true),
('de baby', 'le bébé', 'nl-fr', 'De baby slaapt de hele dag.', true),
('de man', 'l''homme', 'nl-fr', 'De man leest de krant.', true),
('de vrouw', 'la femme', 'nl-fr', 'De vrouw werkt als dokter.', true),
('de jongen', 'le garçon', 'nl-fr', 'De jongen speelt buiten.', true),
('het meisje', 'la fille', 'nl-fr', 'Het meisje zingt prachtig.', true),
('de vriend', 'l''ami', 'nl-fr', 'Mijn vriend helpt me altijd.', true),
('de vriendin', 'l''amie', 'nl-fr', 'Mijn vriendin woont in Utrecht.', true),
('de buur', 'le voisin', 'nl-fr', 'Mijn buur is erg vriendelijk.', true),
('de collega', 'le collègue', 'nl-fr', 'Mijn collega werkt hard.', true),
('de familie', 'la famille', 'nl-fr', 'Mijn familie woont verspreid over Nederland.', true),
('de ouders', 'les parents', 'nl-fr', 'Mijn ouders wonen in Rotterdam.', true),
('de echtgenoot', 'l''époux', 'nl-fr', 'Haar echtgenoot is erg aardig.', true),
('de tweeling', 'les jumeaux', 'nl-fr', 'De tweeling ziet er hetzelfde uit.', true),
('de volwassene', 'l''adulte', 'nl-fr', 'Alleen volwassenen mogen alcohol drinken.', true),
('de bejaarde', 'la personne âgée', 'nl-fr', 'De bejaarde heeft hulp nodig.', true),
('de tiener', 'l''adolescent', 'nl-fr', 'De tiener luistert naar muziek.', true),
('de persoon', 'la personne', 'nl-fr', 'Er was één persoon aanwezig.', true),

-- Food/drinks (65)
('de boter', 'le beurre', 'nl-fr', 'Ik smeer boter op mijn brood.', true),
('de kaas', 'le fromage', 'nl-fr', 'Nederland is bekend om zijn kaas.', true),
('de melk', 'le lait', 'nl-fr', 'Ik drink elke ochtend melk.', true),
('de kip', 'le poulet', 'nl-fr', 'We eten kip met groenten.', true),
('de vis', 'le poisson', 'nl-fr', 'We eten vis op vrijdag.', true),
('de garnaal', 'la crevette', 'nl-fr', 'Garnalen zijn lekker met knoflook.', true),
('de rijst', 'le riz', 'nl-fr', 'We eten rijst met kip.', true),
('de pasta', 'les pâtes', 'nl-fr', 'Ik maak pasta met tomatensaus.', true),
('de aardappel', 'la pomme de terre', 'nl-fr', 'Aardappelen zijn typisch Nederlands.', true),
('de wortel', 'la carotte', 'nl-fr', 'Wortels zijn oranje en gezond.', true),
('de tomaat', 'la tomate', 'nl-fr', 'De tomaat is rood en sappig.', true),
('de ui', 'l''oignon', 'nl-fr', 'De ui maakt mijn ogen wateren.', true),
('de knoflook', 'l''ail', 'nl-fr', 'Knoflook geeft veel smaak.', true),
('de sla', 'la laitue', 'nl-fr', 'Sla is fris en groen.', true),
('de appel', 'la pomme', 'nl-fr', 'Een appel per dag houdt de dokter weg.', true),
('de peer', 'la poire', 'nl-fr', 'De peer is zoet en sappig.', true),
('de banaan', 'la banane', 'nl-fr', 'De banaan is geel en zoet.', true),
('de aardbei', 'la fraise', 'nl-fr', 'Aardbeien zijn lekker in de zomer.', true),
('de druif', 'le raisin', 'nl-fr', 'Druiven groeien in de wijngaard.', true),
('de sinaasappel', 'l''orange', 'nl-fr', 'Sinaasappelsap is lekker bij het ontbijt.', true),
('de citroen', 'le citron', 'nl-fr', 'Citroen is zuur maar lekker in thee.', true),
('de suiker', 'le sucre', 'nl-fr', 'Ik doe suiker in mijn koffie.', true),
('de peper', 'le poivre', 'nl-fr', 'Peper geeft pit aan het gerecht.', true),
('de olie', 'l''huile', 'nl-fr', 'Ik bak de vis in olie.', true),
('de soep', 'la soupe', 'nl-fr', 'De soep is warm en lekker.', true),
('de pizza', 'la pizza', 'nl-fr', 'We bestellen pizza op vrijdagavond.', true),
('de hamburger', 'le hamburger', 'nl-fr', 'Een hamburger is een populair fastfood.', true),
('de taart', 'le gâteau', 'nl-fr', 'We eten taart op haar verjaardag.', true),
('de koffie', 'le café', 'nl-fr', 'Ik drink koffie elke ochtend.', true),
('de thee', 'le thé', 'nl-fr', 'Ik drink thee als ik ziek ben.', true),
('de wijn', 'le vin', 'nl-fr', 'We drinken wijn bij het diner.', true),
('de limonade', 'la limonade', 'nl-fr', 'De kinderen drinken limonade.', true),
('de fles', 'la bouteille', 'nl-fr', 'Ik koop een fles water.', true),
('de vork', 'la fourchette', 'nl-fr', 'Gebruik een vork voor je pasta.', true),
('de lepel', 'la cuillère', 'nl-fr', 'Ik eet soep met een lepel.', true),
('de pan', 'la casserole', 'nl-fr', 'Ik kook de soep in een grote pan.', true),
('de groente', 'les légumes', 'nl-fr', 'Eet elke dag groente voor je gezondheid.', true),
('de maaltijd', 'le repas', 'nl-fr', 'De maaltijd was heerlijk.', true),
('de honger', 'la faim', 'nl-fr', 'Ik heb veel honger na het sporten.', true),
('de dorst', 'la soif', 'nl-fr', 'Ik heb dorst en wil water drinken.', true),
('de friet', 'les frites', 'nl-fr', 'Friet met mayonaise is typisch Belgisch.', true),
('de salade', 'la salade', 'nl-fr', 'Ik eet een salade als lunch.', true),
('het brood', 'le pain', 'nl-fr', 'We eten brood bij het ontbijt.', true),
('het vlees', 'la viande', 'nl-fr', 'Hij eet geen vlees, hij is vegetariër.', true),
('het ei', 'l''œuf', 'nl-fr', 'Ik eet een ei bij het ontbijt.', true),
('het ijs', 'la glace', 'nl-fr', 'In de zomer eet ik graag ijs.', true),
('het glas', 'le verre', 'nl-fr', 'Mag ik een glas water?', true),
('het bord', 'l''assiette', 'nl-fr', 'Het bord is vol met eten.', true),
('het mes', 'le couteau', 'nl-fr', 'Gebruik een mes om het brood te snijden.', true),
('het water', 'l''eau', 'nl-fr', 'Drink genoeg water per dag.', true),
('het fruit', 'les fruits', 'nl-fr', 'Fruit is gezond en lekker.', true),
('het bier', 'la bière', 'nl-fr', 'Nederland is bekend om zijn bier.', true),
('het recept', 'la recette', 'nl-fr', 'Ze volgt een recept voor de taart.', true),
('het ontbijt', 'le petit-déjeuner', 'nl-fr', 'Het ontbijt is de belangrijkste maaltijd.', true),
('het diner', 'le dîner', 'nl-fr', 'Het diner is klaar om zeven uur.', true),
('het menu', 'le menu', 'nl-fr', 'Mag ik het menu zien?', true),
('de maïs', 'le maïs', 'nl-fr', 'Maïs is geel en zoet.', true),
('de champignon', 'le champignon', 'nl-fr', 'Champignons zijn lekker in de saus.', true),
('de spinazie', 'les épinards', 'nl-fr', 'Spinazie is rijk aan ijzer.', true),
('de komkommer', 'le concombre', 'nl-fr', 'Komkommer is fris en koel.', true),
('de paprika', 'le poivron', 'nl-fr', 'Paprika kan rood, geel of groen zijn.', true),
('de saus', 'la sauce', 'nl-fr', 'De saus is lekker bij het vlees.', true),
('het zout', 'le sel', 'nl-fr', 'Voeg wat zout toe aan de soep.', true),
('de mosterd', 'la moutarde', 'nl-fr', 'Mosterd smaakt lekker bij worst.', true),
('de chocolade', 'le chocolat', 'nl-fr', 'Ik eet graag chocolade.', true),

-- Animals (50)
('de hond', 'le chien', 'nl-fr', 'De hond loopt met zijn baasje in het park.', true),
('de kat', 'le chat', 'nl-fr', 'De kat ligt op de bank te slapen.', true),
('de koe', 'la vache', 'nl-fr', 'De koe geeft melk.', true),
('de geit', 'la chèvre', 'nl-fr', 'De geit eet gras op de boerderij.', true),
('de eend', 'le canard', 'nl-fr', 'De eend zwemt in de vijver.', true),
('de muis', 'la souris', 'nl-fr', 'De muis verstopt zich in het gat.', true),
('de vogel', 'l''oiseau', 'nl-fr', 'De vogel zingt vroeg in de ochtend.', true),
('de slang', 'le serpent', 'nl-fr', 'De slang kronkelt door het gras.', true),
('de kikker', 'la grenouille', 'nl-fr', 'De kikker springt in de vijver.', true),
('de beer', 'l''ours', 'nl-fr', 'De beer slaapt in de winter.', true),
('de leeuw', 'le lion', 'nl-fr', 'De leeuw is de koning van de jungle.', true),
('de tijger', 'le tigre', 'nl-fr', 'De tijger heeft oranje strepen.', true),
('de olifant', 'l''éléphant', 'nl-fr', 'De olifant heeft een lange slurf.', true),
('de giraffe', 'la girafe', 'nl-fr', 'De giraffe heeft een zeer lange nek.', true),
('de zebra', 'le zèbre', 'nl-fr', 'De zebra heeft zwart-witte strepen.', true),
('de aap', 'le singe', 'nl-fr', 'De aap klimt in de boom.', true),
('de wolf', 'le loup', 'nl-fr', 'De wolf huilt in de nacht.', true),
('de vos', 'le renard', 'nl-fr', 'De vos is slim en snel.', true),
('de eekhoorn', 'l''écureuil', 'nl-fr', 'De eekhoorn verzamelt noten.', true),
('de vlinder', 'le papillon', 'nl-fr', 'De vlinder vliegt van bloem naar bloem.', true),
('de bij', 'l''abeille', 'nl-fr', 'De bij maakt honing.', true),
('de spin', 'l''araignée', 'nl-fr', 'De spin maakt een web.', true),
('de mug', 'le moustique', 'nl-fr', 'De mug steekt in de zomer.', true),
('de adelaar', 'l''aigle', 'nl-fr', 'De adelaar vliegt hoog in de lucht.', true),
('de uil', 'la chouette', 'nl-fr', 'De uil is actief in de nacht.', true),
('de dolfijn', 'le dauphin', 'nl-fr', 'De dolfijn is erg intelligent.', true),
('de walvis', 'la baleine', 'nl-fr', 'De walvis is het grootste zeedier.', true),
('de haai', 'le requin', 'nl-fr', 'De haai zwemt snel in de zee.', true),
('de krab', 'le crabe', 'nl-fr', 'De krab loopt zijwaarts.', true),
('de schildpad', 'la tortue', 'nl-fr', 'De schildpad beweegt langzaam.', true),
('de krokodil', 'le crocodile', 'nl-fr', 'De krokodil ligt in de rivier.', true),
('de papegaai', 'le perroquet', 'nl-fr', 'De papegaai herhaalt woorden.', true),
('de neushoorn', 'le rhinocéros', 'nl-fr', 'De neushoorn heeft een grote hoorn.', true),
('de kameel', 'le chameau', 'nl-fr', 'De kameel leeft in de woestijn.', true),
('de kangoeroe', 'le kangourou', 'nl-fr', 'De kangoeroe komt uit Australië.', true),
('de pinguïn', 'le pingouin', 'nl-fr', 'De pinguïn leeft in de kou.', true),
('de vlieg', 'la mouche', 'nl-fr', 'De vlieg vliegt om het eten.', true),
('de mier', 'la fourmi', 'nl-fr', 'De mier werkt hard in de kolonie.', true),
('de libelle', 'la libellule', 'nl-fr', 'De libelle vliegt boven het water.', true),
('de kreeft', 'le homard', 'nl-fr', 'De kreeft wordt rood als hij gekookt wordt.', true),
('de octopus', 'la pieuvre', 'nl-fr', 'De octopus heeft acht armen.', true),
('de lama', 'le lama', 'nl-fr', 'De lama leeft in Zuid-Amerika.', true),
('de rat', 'le rat', 'nl-fr', 'De rat verstopt zich in de kelder.', true),
('de haas', 'le lièvre', 'nl-fr', 'De haas rent erg snel.', true),
('het schaap', 'le mouton', 'nl-fr', 'Het schaap geeft wol.', true),
('het paard', 'le cheval', 'nl-fr', 'Het paard galoppeert over het veld.', true),
('het varken', 'le cochon', 'nl-fr', 'Het varken wentelt zich in de modder.', true),
('het konijn', 'le lapin', 'nl-fr', 'Het konijn eet wortels.', true),
('het hert', 'le cerf', 'nl-fr', 'Het hert heeft grote geweien.', true),
('het nijlpaard', 'l''hippopotame', 'nl-fr', 'Het nijlpaard leeft bij de rivier.', true),

-- Nature (28)
('de boom', 'l''arbre', 'nl-fr', 'De boom heeft veel bladeren.', true),
('de bloem', 'la fleur', 'nl-fr', 'De bloem geurt heerlijk.', true),
('de plant', 'la plante', 'nl-fr', 'Ik geef water aan mijn plant.', true),
('de tak', 'la branche', 'nl-fr', 'De vogel zit op de tak.', true),
('de berg', 'la montagne', 'nl-fr', 'We wandelen de berg op.', true),
('de rivier', 'la rivière', 'nl-fr', 'De rivier stroomt naar de zee.', true),
('de zee', 'la mer', 'nl-fr', 'We zwemmen in de zee.', true),
('de oceaan', 'l''océan', 'nl-fr', 'De oceaan is enorm groot.', true),
('de waterval', 'la cascade', 'nl-fr', 'De waterval is prachtig.', true),
('de vulkaan', 'le volcan', 'nl-fr', 'De vulkaan spuwt lava.', true),
('de steen', 'la pierre', 'nl-fr', 'Hij gooit een steen in het water.', true),
('de aarde', 'la terre', 'nl-fr', 'De aarde is onze planeet.', true),
('de ster', 'l''étoile', 'nl-fr', 'De sterren schijnen in de nacht.', true),
('de maan', 'la lune', 'nl-fr', 'De maan is vol vanavond.', true),
('de planeet', 'la planète', 'nl-fr', 'De aarde is een planeet.', true),
('de natuur', 'la nature', 'nl-fr', 'Ik hou van de natuur.', true),
('de horizon', 'l''horizon', 'nl-fr', 'De zon zakt achter de horizon.', true),
('het gras', 'l''herbe', 'nl-fr', 'Het gras is groen na de regen.', true),
('het blad', 'la feuille', 'nl-fr', 'Het blad valt in de herfst.', true),
('het bos', 'la forêt', 'nl-fr', 'We wandelen in het bos.', true),
('het park', 'le parc', 'nl-fr', 'We picknicken in het park.', true),
('het meer', 'le lac', 'nl-fr', 'We zwemmen in het meer.', true),
('het strand', 'la plage', 'nl-fr', 'We liggen op het strand.', true),
('het eiland', 'l''île', 'nl-fr', 'Het eiland is omringd door water.', true),
('het zand', 'le sable', 'nl-fr', 'Het zand is warm op het strand.', true),
('het milieu', 'l''environnement', 'nl-fr', 'We moeten het milieu beschermen.', true),
('het veld', 'le champ', 'nl-fr', 'De koeien grazen in het veld.', true),
('het land', 'le pays', 'nl-fr', 'Nederland is een mooi land.', true),

-- House/furniture (48)
('de kamer', 'la pièce', 'nl-fr', 'Er zijn vijf kamers in ons huis.', true),
('de woonkamer', 'le salon', 'nl-fr', 'We zitten in de woonkamer.', true),
('de slaapkamer', 'la chambre à coucher', 'nl-fr', 'Mijn slaapkamer is blauw geschilderd.', true),
('de badkamer', 'la salle de bain', 'nl-fr', 'De badkamer is op de eerste verdieping.', true),
('de keuken', 'la cuisine', 'nl-fr', 'Ik kook in de keuken.', true),
('de eetkamer', 'la salle à manger', 'nl-fr', 'We eten in de eetkamer.', true),
('de gang', 'le couloir', 'nl-fr', 'De jassen hangen in de gang.', true),
('de trap', 'l''escalier', 'nl-fr', 'Ik loop de trap op naar boven.', true),
('de deur', 'la porte', 'nl-fr', 'Doe de deur dicht, het is koud.', true),
('de vloer', 'le sol', 'nl-fr', 'De vloer is van hout.', true),
('de muur', 'le mur', 'nl-fr', 'De muur is wit geschilderd.', true),
('de garage', 'le garage', 'nl-fr', 'De auto staat in de garage.', true),
('de kelder', 'la cave', 'nl-fr', 'We bewaren wijn in de kelder.', true),
('de zolder', 'le grenier', 'nl-fr', 'De kerstspullen liggen op de zolder.', true),
('de tafel', 'la table', 'nl-fr', 'We eten aan de tafel.', true),
('de stoel', 'la chaise', 'nl-fr', 'Ga zitten op de stoel.', true),
('de bank', 'le canapé', 'nl-fr', 'We zitten op de bank.', true),
('de kast', 'l''armoire', 'nl-fr', 'De kleren hangen in de kast.', true),
('de lamp', 'la lampe', 'nl-fr', 'Zet de lamp aan, het is donker.', true),
('de spiegel', 'le miroir', 'nl-fr', 'Ik kijk in de spiegel.', true),
('de koelkast', 'le réfrigérateur', 'nl-fr', 'De melk staat in de koelkast.', true),
('de oven', 'le four', 'nl-fr', 'De taart bakt in de oven.', true),
('de wasmachine', 'le lave-linge', 'nl-fr', 'De wasmachine draait.', true),
('de douche', 'la douche', 'nl-fr', 'Ik neem elke ochtend een douche.', true),
('de zeep', 'le savon', 'nl-fr', 'Was je handen met zeep.', true),
('de handdoek', 'la serviette', 'nl-fr', 'De handdoek hangt aan de deur.', true),
('de sleutel', 'la clé', 'nl-fr', 'Ik ben mijn sleutel kwijt.', true),
('de bel', 'la sonnette', 'nl-fr', 'De bel klinkt aan de voordeur.', true),
('de tv', 'la télévision', 'nl-fr', 'We kijken tv na het eten.', true),
('de verdieping', 'l''étage', 'nl-fr', 'We wonen op de derde verdieping.', true),
('de lift', 'l''ascenseur', 'nl-fr', 'We nemen de lift naar boven.', true),
('de haag', 'la haie', 'nl-fr', 'De haag scheidt de tuinen.', true),
('de brievenbus', 'la boîte aux lettres', 'nl-fr', 'Er ligt post in de brievenbus.', true),
('de woning', 'le logement', 'nl-fr', 'Ze zoeken een betaalbare woning.', true),
('het huis', 'la maison', 'nl-fr', 'Ons huis heeft een grote tuin.', true),
('het appartement', 'l''appartement', 'nl-fr', 'Ze woont in een appartement in de stad.', true),
('het raam', 'la fenêtre', 'nl-fr', 'Ik open het raam voor frisse lucht.', true),
('het plafond', 'le plafond', 'nl-fr', 'Het plafond is hoog in dit huis.', true),
('het dak', 'le toit', 'nl-fr', 'Het dak lekt bij regen.', true),
('het bed', 'le lit', 'nl-fr', 'Ik ga naar bed om tien uur.', true),
('het bad', 'la baignoire', 'nl-fr', 'Ik neem een bad voor het slapengaan.', true),
('het toilet', 'les toilettes', 'nl-fr', 'Het toilet is de gang door.', true),
('het tapijt', 'le tapis', 'nl-fr', 'Het tapijt is zacht onder mijn voeten.', true),
('het gordijn', 'le rideau', 'nl-fr', 'Ik doe het gordijn dicht in de avond.', true),
('het bureau', 'le bureau', 'nl-fr', 'Ik werk aan mijn bureau thuis.', true),
('het balkon', 'le balcon', 'nl-fr', 'We zitten op het balkon in de zon.', true),
('het terras', 'la terrasse', 'nl-fr', 'We eten buiten op het terras.', true),
('het adres', 'l''adresse', 'nl-fr', 'Wat is uw adres?', true),
('het kussen', 'le coussin', 'nl-fr', 'Het kussen op de bank is zacht.', true),

-- Clothes (35)
('de kleren', 'les vêtements', 'nl-fr', 'Ik koop nieuwe kleren in de winkel.', true),
('de trui', 'le pull', 'nl-fr', 'Ik draag een warme trui in de winter.', true),
('de broek', 'le pantalon', 'nl-fr', 'Hij draagt een blauwe broek.', true),
('de rok', 'la jupe', 'nl-fr', 'Ze draagt een rode rok.', true),
('de jurk', 'la robe', 'nl-fr', 'Ze draagt een mooie jurk op het feest.', true),
('de jas', 'le manteau', 'nl-fr', 'Doe je jas aan, het is koud.', true),
('de regenjas', 'l''imperméable', 'nl-fr', 'Neem je regenjas mee, het gaat regenen.', true),
('de sjaal', 'l''écharpe', 'nl-fr', 'De sjaal houdt mijn nek warm.', true),
('de hoed', 'le chapeau', 'nl-fr', 'Hij draagt een hoed in de zon.', true),
('de pet', 'la casquette', 'nl-fr', 'De jongen draagt een pet.', true),
('de handschoenen', 'les gants', 'nl-fr', 'Ik doe handschoenen aan als het vriest.', true),
('de sokken', 'les chaussettes', 'nl-fr', 'Ik draag warme sokken in de winter.', true),
('de schoenen', 'les chaussures', 'nl-fr', 'Mijn schoenen zijn nat van de regen.', true),
('de laarzen', 'les bottes', 'nl-fr', 'Ze draagt laarzen in de regen.', true),
('de sandalen', 'les sandales', 'nl-fr', 'In de zomer draag ik sandalen.', true),
('de riem', 'la ceinture', 'nl-fr', 'Zijn riem is van leer.', true),
('de das', 'la cravate', 'nl-fr', 'Hij draagt een das bij zijn pak.', true),
('de tas', 'le sac', 'nl-fr', 'Mijn tas is te zwaar.', true),
('de rugzak', 'le sac à dos', 'nl-fr', 'De leerling draagt een rugzak.', true),
('de portemonnee', 'le portefeuille', 'nl-fr', 'Ik verloor mijn portemonnee.', true),
('de ring', 'la bague', 'nl-fr', 'Ze draagt een gouden ring.', true),
('de ketting', 'le collier', 'nl-fr', 'Ze draagt een zilveren ketting.', true),
('de oorbel', 'la boucle d''oreille', 'nl-fr', 'Ze draagt gouden oorbellen.', true),
('de muts', 'le bonnet', 'nl-fr', 'Draag een muts als het koud is.', true),
('de rits', 'la fermeture éclair', 'nl-fr', 'De rits van mijn jas is kapot.', true),
('de knoop', 'le bouton', 'nl-fr', 'Een knoop is los van mijn hemd.', true),
('het shirt', 'le t-shirt', 'nl-fr', 'Ik draag een wit shirt.', true),
('het pyama', 'le pyjama', 'nl-fr', 'Ik trek mijn pyama aan voor het slapengaan.', true),
('het horloge', 'la montre', 'nl-fr', 'Mijn horloge loopt voor.', true),
('het uniform', 'l''uniforme', 'nl-fr', 'De politieagent draagt een uniform.', true),
('het zwempak', 'le maillot de bain', 'nl-fr', 'Ze draagt een rood zwempak.', true),
('het vest', 'le gilet', 'nl-fr', 'Ik draag een vest over mijn shirt.', true),
('het hemd', 'la chemise', 'nl-fr', 'Hij draagt een wit hemd.', true),
('het pak', 'le costume', 'nl-fr', 'Hij draagt een pak naar de vergadering.', true),
('de lippenstift', 'le rouge à lèvres', 'nl-fr', 'Ze draagt rode lippenstift.', true),

-- Transport (28)
('de auto', 'la voiture', 'nl-fr', 'We rijden met de auto naar het strand.', true),
('de fiets', 'le vélo', 'nl-fr', 'Ik ga op de fiets naar het werk.', true),
('de motor', 'la moto', 'nl-fr', 'Hij rijdt op een motor.', true),
('de bus', 'le bus', 'nl-fr', 'Ik neem de bus naar school.', true),
('de trein', 'le train', 'nl-fr', 'De trein vertrekt om negen uur.', true),
('de metro', 'le métro', 'nl-fr', 'We nemen de metro in de stad.', true),
('de tram', 'le tram', 'nl-fr', 'De tram rijdt door het centrum.', true),
('de boot', 'le bateau', 'nl-fr', 'We varen met de boot over het meer.', true),
('de taxi', 'le taxi', 'nl-fr', 'We nemen een taxi naar het vliegveld.', true),
('de vrachtwagen', 'le camion', 'nl-fr', 'De vrachtwagen brengt de goederen.', true),
('de benzine', 'l''essence', 'nl-fr', 'Ik moet benzine tanken.', true),
('de luchthaven', 'l''aéroport', 'nl-fr', 'Het vliegtuig landt op de luchthaven.', true),
('de haven', 'le port', 'nl-fr', 'De boot vertrekt vanuit de haven.', true),
('de weg', 'la route', 'nl-fr', 'De weg is glad door de regen.', true),
('de straat', 'la rue', 'nl-fr', 'We wonen in een rustige straat.', true),
('de brug', 'le pont', 'nl-fr', 'We rijden over de brug.', true),
('de tunnel', 'le tunnel', 'nl-fr', 'De trein rijdt door de tunnel.', true),
('de rotonde', 'le rond-point', 'nl-fr', 'Neem de tweede afslag bij de rotonde.', true),
('de snelweg', 'l''autoroute', 'nl-fr', 'We rijden op de snelweg naar Antwerpen.', true),
('de halte', 'l''arrêt', 'nl-fr', 'Ik wacht bij de bushalte.', true),
('de bagage', 'les bagages', 'nl-fr', 'Mijn bagage is te zwaar.', true),
('de parkeerplaats', 'le parking', 'nl-fr', 'Er is geen parkeerplaats meer vrij.', true),
('het vliegtuig', 'l''avion', 'nl-fr', 'Het vliegtuig vertrekt om tien uur.', true),
('het station', 'la gare', 'nl-fr', 'Ik wacht op je bij het station.', true),
('het kaartje', 'le billet', 'nl-fr', 'Ik koop een kaartje voor de trein.', true),
('het perron', 'le quai', 'nl-fr', 'De trein staat op perron drie.', true),
('het rijbewijs', 'le permis de conduire', 'nl-fr', 'Ik heb mijn rijbewijs gehaald.', true),
('het verkeer', 'la circulation', 'nl-fr', 'Er is veel verkeer op de snelweg.', true),

-- School/work (40)
('de school', 'l''école', 'nl-fr', 'De kinderen gaan naar school.', true),
('de klas', 'la classe', 'nl-fr', 'Er zijn twintig leerlingen in de klas.', true),
('de leerling', 'l''élève', 'nl-fr', 'De leerling maakt zijn huiswerk.', true),
('de leraar', 'le professeur', 'nl-fr', 'De leraar legt de les uit.', true),
('de pen', 'le stylo', 'nl-fr', 'Ik schrijf met een blauwe pen.', true),
('de gum', 'la gomme', 'nl-fr', 'Ik gebruik de gum om fouten te wissen.', true),
('de les', 'le cours', 'nl-fr', 'De les begint om acht uur.', true),
('de taal', 'la langue', 'nl-fr', 'Ik leer een nieuwe taal.', true),
('de universiteit', 'l''université', 'nl-fr', 'Ze studeert aan de universiteit.', true),
('de baan', 'l''emploi', 'nl-fr', 'Hij heeft een nieuwe baan gevonden.', true),
('de vergadering', 'la réunion', 'nl-fr', 'We hebben een vergadering om twee uur.', true),
('de e-mail', 'l''e-mail', 'nl-fr', 'Ik stuur je een e-mail.', true),
('de brief', 'la lettre', 'nl-fr', 'Ik schrijf een brief aan mijn oma.', true),
('de vakantie', 'les vacances', 'nl-fr', 'In juli hebben we vakantie.', true),
('de baas', 'le patron', 'nl-fr', 'Mijn baas is streng maar eerlijk.', true),
('de stage', 'le stage', 'nl-fr', 'Ze doet stage bij een groot bedrijf.', true),
('de deadline', 'la date limite', 'nl-fr', 'De deadline is morgen.', true),
('de geschiedenis', 'l''histoire', 'nl-fr', 'Ik studeer geschiedenis op de universiteit.', true),
('de aardrijkskunde', 'la géographie', 'nl-fr', 'We leren over landen in aardrijkskunde.', true),
('de kunst', 'l''art', 'nl-fr', 'Ze houdt van kunst en muziek.', true),
('de muziek', 'la musique', 'nl-fr', 'Muziek maakt mensen gelukkig.', true),
('de bibliotheek', 'la bibliothèque', 'nl-fr', 'Ik leen boeken uit de bibliotheek.', true),
('de computer', 'l''ordinateur', 'nl-fr', 'Ik werk op mijn computer.', true),
('de toets', 'le test', 'nl-fr', 'Morgen heb ik een moeilijke toets.', true),
('de boekentas', 'le cartable', 'nl-fr', 'Mijn boekentas is zwaar.', true),
('het boek', 'le livre', 'nl-fr', 'Ik lees een spannend boek.', true),
('het schrift', 'le cahier', 'nl-fr', 'Ik schrijf in mijn schrift.', true),
('het potlood', 'le crayon', 'nl-fr', 'Ik teken met een potlood.', true),
('het werk', 'le travail', 'nl-fr', 'Ik ga naar mijn werk.', true),
('het huiswerk', 'les devoirs', 'nl-fr', 'Ik maak mijn huiswerk na school.', true),
('het examen', 'l''examen', 'nl-fr', 'Ik studeer hard voor mijn examen.', true),
('het cijfer', 'la note', 'nl-fr', 'Ik heb een goed cijfer gehaald.', true),
('het diploma', 'le diplôme', 'nl-fr', 'Ze heeft haar diploma gehaald.', true),
('het salaris', 'le salaire', 'nl-fr', 'Het salaris wordt maandelijks betaald.', true),
('het bedrijf', 'l''entreprise', 'nl-fr', 'Ze werkt bij een groot bedrijf.', true),
('het kantoor', 'le bureau (lieu)', 'nl-fr', 'Ik werk op kantoor van negen tot vijf.', true),
('het rapport', 'le rapport', 'nl-fr', 'Ik schrijf een rapport voor mijn baas.', true),
('het project', 'le projet', 'nl-fr', 'We werken aan een groot project.', true),
('het ontslag', 'le licenciement', 'nl-fr', 'Hij kreeg ontslag van zijn baas.', true),
('de wiskunde', 'les mathématiques', 'nl-fr', 'Wiskunde is mijn moeilijkste vak.', true),

-- Health (25)
('de gezondheid', 'la santé', 'nl-fr', 'Gezondheid is het belangrijkste.', true),
('de pijn', 'la douleur', 'nl-fr', 'Ik heb pijn in mijn rug.', true),
('de koorts', 'la fièvre', 'nl-fr', 'Het kind heeft koorts.', true),
('de griep', 'la grippe', 'nl-fr', 'Ik heb griep en moet thuis blijven.', true),
('de hoofdpijn', 'le mal de tête', 'nl-fr', 'Ik heb hoofdpijn van het werken.', true),
('de buikpijn', 'le mal de ventre', 'nl-fr', 'Ik heb buikpijn na het eten.', true),
('de allergie', 'l''allergie', 'nl-fr', 'Ze heeft een allergie voor noten.', true),
('de wond', 'la blessure', 'nl-fr', 'De wond moet verbonden worden.', true),
('de dokter', 'le médecin', 'nl-fr', 'Ik ga naar de dokter omdat ik ziek ben.', true),
('de verpleegkundige', 'l''infirmier', 'nl-fr', 'De verpleegkundige zorgt voor de patiënten.', true),
('de pil', 'le comprimé', 'nl-fr', 'Ik neem een pil voor de pijn.', true),
('de apotheek', 'la pharmacie', 'nl-fr', 'Ik haal mijn medicijnen bij de apotheek.', true),
('de rust', 'le repos', 'nl-fr', 'Je hebt rust nodig om te herstellen.', true),
('de operatie', 'l''opération', 'nl-fr', 'De operatie was een succes.', true),
('de tandarts', 'le dentiste', 'nl-fr', 'Ik ga twee keer per jaar naar de tandarts.', true),
('de ambulance', 'l''ambulance', 'nl-fr', 'De ambulance reed snel naar het ziekenhuis.', true),
('de bloeddruk', 'la tension artérielle', 'nl-fr', 'Mijn bloeddruk is te hoog.', true),
('de vitamine', 'la vitamine', 'nl-fr', 'Ik neem vitaminen in de winter.', true),
('de ziekte', 'la maladie', 'nl-fr', 'De ziekte duurt al twee weken.', true),
('het ziekenhuis', 'l''hôpital', 'nl-fr', 'Hij ligt in het ziekenhuis.', true),
('het medicijn', 'le médicament', 'nl-fr', 'De dokter schrijft een medicijn voor.', true),
('het herstel', 'le rétablissement', 'nl-fr', 'Het herstel duurt enkele weken.', true),
('het dieet', 'le régime alimentaire', 'nl-fr', 'Ze volgt een gezond dieet.', true),
('het gewicht', 'le poids', 'nl-fr', 'Zijn gewicht is stabiel.', true),
('de bloedgroep', 'le groupe sanguin', 'nl-fr', 'Mijn bloedgroep is A positief.', true),

-- Sports/hobbies (30)
('de gitaar', 'la guitare', 'nl-fr', 'Hij speelt gitaar in een band.', true),
('de piano', 'le piano', 'nl-fr', 'Ze leert piano spelen.', true),
('de wedstrijd', 'le match', 'nl-fr', 'We kijken naar de wedstrijd.', true),
('de club', 'le club', 'nl-fr', 'Ik ben lid van een sportclub.', true),
('de trainer', 'l''entraîneur', 'nl-fr', 'De trainer geeft instructies aan de spelers.', true),
('de speler', 'le joueur', 'nl-fr', 'De speler scoort een doelpunt.', true),
('de hobby', 'le loisir', 'nl-fr', 'Mijn hobby is schilderen.', true),
('de sport', 'le sport', 'nl-fr', 'Sport is goed voor je gezondheid.', true),
('de film', 'le film', 'nl-fr', 'We gaan een film kijken in de bioscoop.', true),
('de muzikant', 'le musicien', 'nl-fr', 'De muzikant speelt elke avond.', true),
('de schilder', 'le peintre', 'nl-fr', 'De schilder werkt aan een nieuw schilderij.', true),
('het kampioenschap', 'le championnat', 'nl-fr', 'Nederland won het kampioenschap.', true),
('het team', 'l''équipe', 'nl-fr', 'Ons team heeft gewonnen.', true),
('het golf', 'le golf', 'nl-fr', 'Hij speelt golf op zondag.', true),
('het hockey', 'le hockey', 'nl-fr', 'Ze speelt hockey voor een club.', true),
('het voetbal', 'le football', 'nl-fr', 'Voetbal is erg populair in Nederland.', true),
('het basketbal', 'le basketball', 'nl-fr', 'Hij speelt basketbal in een team.', true),
('het tennis', 'le tennis', 'nl-fr', 'Ze speelt tennis elke zondag.', true),
('het spel', 'le jeu', 'nl-fr', 'We spelen een bordspel na het eten.', true),
('het zwemmen', 'la natation', 'nl-fr', 'Zwemmen is goed voor je gezondheid.', true),
('het fietsen', 'le cyclisme', 'nl-fr', 'Fietsen is populair in Nederland.', true),
('het schilderen', 'la peinture', 'nl-fr', 'Schilderen is haar favoriete hobby.', true),
('het koken', 'la cuisine', 'nl-fr', 'Koken is zijn grote passie.', true),
('het dansen', 'la danse', 'nl-fr', 'Ze gaat dansen op zaterdagavond.', true),
('het zingen', 'le chant', 'nl-fr', 'Hij zingt in een koor.', true),
('het reizen', 'le voyage', 'nl-fr', 'Reizen is haar grootste passie.', true),
('het fotograferen', 'la photographie', 'nl-fr', 'Hij fotografeert landschappen.', true),
('het wandelen', 'la randonnée', 'nl-fr', 'We gaan wandelen in het bos.', true),
('het lopen', 'la course à pied', 'nl-fr', 'Ze gaat elke ochtend lopen.', true),
('het lezen', 'la lecture', 'nl-fr', 'Lezen is goed voor je brein.', true),

-- Technology (20)
('de laptop', 'le laptop', 'nl-fr', 'Ik werk op mijn laptop.', true),
('de tablet', 'la tablette', 'nl-fr', 'Hij leest op zijn tablet.', true),
('de telefoon', 'le téléphone', 'nl-fr', 'De telefoon gaat over.', true),
('de smartphone', 'le smartphone', 'nl-fr', 'Iedereen heeft een smartphone.', true),
('de website', 'le site web', 'nl-fr', 'Ik zoek informatie op de website.', true),
('de app', 'l''application', 'nl-fr', 'Ze downloadt een nieuwe app.', true),
('de printer', 'l''imprimante', 'nl-fr', 'De printer is kapot.', true),
('de camera', 'l''appareil photo', 'nl-fr', 'Hij maakt foto''s met zijn camera.', true),
('de televisie', 'la télévision', 'nl-fr', 'We kijken televisie na het eten.', true),
('de radio', 'la radio', 'nl-fr', 'Ik luister naar de radio in de auto.', true),
('de batterij', 'la batterie', 'nl-fr', 'Mijn telefoon heeft een lege batterij.', true),
('de oplader', 'le chargeur', 'nl-fr', 'Heb jij een oplader voor mijn telefoon?', true),
('het scherm', 'l''écran', 'nl-fr', 'Het scherm is gebroken.', true),
('het toetsenbord', 'le clavier', 'nl-fr', 'Ik typ op het toetsenbord.', true),
('het programma', 'le logiciel', 'nl-fr', 'Ik installeer een nieuw programma.', true),
('het internet', 'l''internet', 'nl-fr', 'Het internet werkt traag vandaag.', true),
('het wifi', 'le wifi', 'nl-fr', 'Wat is het wifi-wachtwoord?', true),
('het wachtwoord', 'le mot de passe', 'nl-fr', 'Ik ben mijn wachtwoord vergeten.', true),
('de computermuis', 'la souris d''ordinateur', 'nl-fr', 'Ik klik met de computermuis.', true),
('de USB-stick', 'la clé USB', 'nl-fr', 'Ik sla de bestanden op op een USB-stick.', true),

-- Shopping/money (20)
('de winkel', 'le magasin', 'nl-fr', 'Ik ga naar de winkel voor boodschappen.', true),
('de markt', 'le marché', 'nl-fr', 'Op zaterdag is er een markt in het centrum.', true),
('de prijs', 'le prix', 'nl-fr', 'De prijs van dit shirt is te hoog.', true),
('de euro', 'l''euro', 'nl-fr', 'Dit kost tien euro.', true),
('de korting', 'la réduction', 'nl-fr', 'Er is twintig procent korting.', true),
('de rekening', 'la facture', 'nl-fr', 'Mag ik de rekening?', true),
('de creditcard', 'la carte de crédit', 'nl-fr', 'Ik betaal met mijn creditcard.', true),
('de bon', 'le reçu', 'nl-fr', 'Bewaar je bon voor de garantie.', true),
('de kassa', 'la caisse', 'nl-fr', 'Ik sta in de rij bij de kassa.', true),
('de boodschappen', 'les courses', 'nl-fr', 'Ik ga boodschappen doen.', true),
('de supermarkt', 'le supermarché', 'nl-fr', 'Ik koop mijn eten in de supermarkt.', true),
('de aanbieding', 'la promotion', 'nl-fr', 'Dit product is in de aanbieding.', true),
('het geld', 'l''argent', 'nl-fr', 'Ik heb geen geld meer.', true),
('het wisselgeld', 'la monnaie', 'nl-fr', 'Mag ik wisselgeld van tien euro?', true),
('de pinpas', 'la carte bancaire', 'nl-fr', 'Ik betaal met mijn pinpas.', true),
('de bankrekening', 'le compte bancaire', 'nl-fr', 'Geld staat op mijn bankrekening.', true),
('de belasting', 'l''impôt', 'nl-fr', 'We betalen belasting aan de overheid.', true),
('de verzekering', 'l''assurance', 'nl-fr', 'Ik heb een ziektekostenverzekering.', true),
('de factuur', 'la facture (formelle)', 'nl-fr', 'Ik ontvang de factuur per e-mail.', true),
('de aankoop', 'l''achat', 'nl-fr', 'Mijn aankoop werd geleverd.', true),

-- Common verbs (100)
('zijn', 'être', 'nl-fr', 'Ik ben gelukkig vandaag.', true),
('hebben', 'avoir', 'nl-fr', 'Ik heb een hond.', true),
('doen', 'faire', 'nl-fr', 'Wat doe jij vandaag?', true),
('gaan', 'aller', 'nl-fr', 'We gaan naar het strand.', true),
('komen', 'venir', 'nl-fr', 'Ze komt morgen aan.', true),
('zien', 'voir', 'nl-fr', 'Ik zie een vogel in de boom.', true),
('horen', 'entendre', 'nl-fr', 'Ik hoor muziek van buiten.', true),
('spreken', 'parler', 'nl-fr', 'Ik spreek Nederlands en Frans.', true),
('zeggen', 'dire', 'nl-fr', 'Wat zeg jij?', true),
('vragen', 'demander', 'nl-fr', 'Hij vraagt om hulp.', true),
('antwoorden', 'répondre', 'nl-fr', 'Ze antwoordt op de vraag.', true),
('weten', 'savoir', 'nl-fr', 'Ik weet het antwoord.', true),
('denken', 'penser', 'nl-fr', 'Ik denk dat je gelijk hebt.', true),
('geloven', 'croire', 'nl-fr', 'Ik geloof hem niet.', true),
('willen', 'vouloir', 'nl-fr', 'Ik wil een kopje koffie.', true),
('kunnen', 'pouvoir', 'nl-fr', 'Ik kan goed zwemmen.', true),
('moeten', 'devoir', 'nl-fr', 'Ik moet morgen vroeg opstaan.', true),
('mogen', 'avoir le droit de', 'nl-fr', 'Mag ik hier parkeren?', true),
('lopen', 'marcher', 'nl-fr', 'We lopen elke ochtend.', true),
('rennen', 'courir', 'nl-fr', 'Hij rent naar de bushalte.', true),
('zitten', 'être assis', 'nl-fr', 'Ze zit op de bank.', true),
('staan', 'être debout', 'nl-fr', 'Hij staat voor de deur.', true),
('liggen', 'être allongé', 'nl-fr', 'Ze ligt op het strand.', true),
('slapen', 'dormir', 'nl-fr', 'De baby slaapt al.', true),
('eten', 'manger', 'nl-fr', 'We eten om zes uur.', true),
('drinken', 'boire', 'nl-fr', 'Ik drink water na het sporten.', true),
('koken', 'cuisiner', 'nl-fr', 'Hij kookt elke avond.', true),
('wassen', 'laver', 'nl-fr', 'Ik was mijn kleren op maandag.', true),
('schoonmaken', 'nettoyer', 'nl-fr', 'We maken het huis schoon op zaterdag.', true),
('werken', 'travailler', 'nl-fr', 'Ze werkt van negen tot vijf.', true),
('studeren', 'étudier', 'nl-fr', 'Hij studeert rechten.', true),
('spelen', 'jouer', 'nl-fr', 'De kinderen spelen in de tuin.', true),
('lezen', 'lire', 'nl-fr', 'Ze leest een boek voor het slapen.', true),
('schrijven', 'écrire', 'nl-fr', 'Ik schrijf een brief.', true),
('zingen', 'chanter', 'nl-fr', 'Ze zingt in een koor.', true),
('luisteren', 'écouter', 'nl-fr', 'Ik luister naar muziek.', true),
('kijken', 'regarder', 'nl-fr', 'We kijken naar een film.', true),
('wachten', 'attendre', 'nl-fr', 'Ik wacht op de bus.', true),
('helpen', 'aider', 'nl-fr', 'Hij helpt zijn vriend met het huiswerk.', true),
('geven', 'donner', 'nl-fr', 'Ze geeft een cadeau aan haar moeder.', true),
('nemen', 'prendre', 'nl-fr', 'Ik neem de trein naar Amsterdam.', true),
('brengen', 'apporter', 'nl-fr', 'Hij brengt de kinderen naar school.', true),
('halen', 'aller chercher', 'nl-fr', 'Ik haal de kinderen op van school.', true),
('zoeken', 'chercher', 'nl-fr', 'Ze zoekt haar sleutels.', true),
('vinden', 'trouver', 'nl-fr', 'Ik heb mijn portemonnee gevonden.', true),
('verliezen', 'perdre', 'nl-fr', 'Hij verloor zijn telefoon.', true),
('winnen', 'gagner', 'nl-fr', 'Ons team heeft gewonnen.', true),
('beginnen', 'commencer', 'nl-fr', 'De les begint om acht uur.', true),
('stoppen', 'arrêter', 'nl-fr', 'De bus stopt hier.', true),
('openen', 'ouvrir', 'nl-fr', 'Open de deur, alsjeblieft.', true),
('sluiten', 'fermer', 'nl-fr', 'Sluit het raam als je weggaat.', true),
('rijden', 'conduire', 'nl-fr', 'Ze rijdt elke dag naar haar werk.', true),
('vliegen', 'voler', 'nl-fr', 'We vliegen naar Spanje.', true),
('zwemmen', 'nager', 'nl-fr', 'Ik zwem elke zaterdag.', true),
('proberen', 'essayer', 'nl-fr', 'Probeer het nog een keer.', true),
('vergeten', 'oublier', 'nl-fr', 'Ik heb mijn tas vergeten.', true),
('herinneren', 'se souvenir', 'nl-fr', 'Ik herinner me zijn naam niet.', true),
('begrijpen', 'comprendre', 'nl-fr', 'Ik begrijp je niet.', true),
('uitleggen', 'expliquer', 'nl-fr', 'Kun je het uitleggen?', true),
('lachen', 'rire', 'nl-fr', 'Ze lacht om de grap.', true),
('huilen', 'pleurer', 'nl-fr', 'Het kind huilt omdat het gevallen is.', true),
('glimlachen', 'sourire', 'nl-fr', 'Ze glimlacht altijd.', true),
('bellen', 'téléphoner', 'nl-fr', 'Ik bel je morgen.', true),
('sturen', 'envoyer', 'nl-fr', 'Ik stuur je een bericht.', true),
('ontvangen', 'recevoir', 'nl-fr', 'Ik heb een brief ontvangen.', true),
('organiseren', 'organiser', 'nl-fr', 'Ze organiseert een feestje.', true),
('plannen', 'planifier', 'nl-fr', 'Ik plan mijn vakantie.', true),
('beslissen', 'décider', 'nl-fr', 'We beslissen morgen.', true),
('kiezen', 'choisir', 'nl-fr', 'Kies een kleur.', true),
('veranderen', 'changer', 'nl-fr', 'Alles verandert met de tijd.', true),
('groeien', 'grandir', 'nl-fr', 'De plant groeit snel.', true),
('bouwen', 'construire', 'nl-fr', 'Ze bouwen een nieuw huis.', true),
('maken', 'fabriquer', 'nl-fr', 'Ik maak een cake.', true),
('breken', 'casser', 'nl-fr', 'Hij breekt het glas per ongeluk.', true),
('repareren', 'réparer', 'nl-fr', 'Ik repareer mijn fiets.', true),
('meten', 'mesurer', 'nl-fr', 'Ze meet de lengte van de kamer.', true),
('tellen', 'compter', 'nl-fr', 'Het kind leert tellen.', true),
('reserveren', 'réserver', 'nl-fr', 'Ik reserveer een tafel in het restaurant.', true),
('bestellen', 'commander', 'nl-fr', 'We bestellen pizza voor vanavond.', true),
('controleren', 'vérifier', 'nl-fr', 'Controleer je werk voor je het inlevert.', true),
('ontmoeten', 'rencontrer', 'nl-fr', 'Ik ontmoet mijn vriend in het park.', true),
('bezoeken', 'visiter', 'nl-fr', 'We bezoeken het museum.', true),
('vertrekken', 'partir', 'nl-fr', 'De trein vertrekt om negen uur.', true),
('aankomen', 'arriver', 'nl-fr', 'We komen aan in Parijs om drie uur.', true),
('terugkeren', 'revenir', 'nl-fr', 'Ze keert terug na haar vakantie.', true),
('dromen', 'rêver', 'nl-fr', 'Ik droom van een vakantie op het strand.', true),
('hopen', 'espérer', 'nl-fr', 'Ik hoop dat het morgen mooi weer is.', true),
('verwachten', 'attendre à', 'nl-fr', 'Ik verwacht een pakketje.', true),
('feliciteren', 'féliciter', 'nl-fr', 'Ik feliciteer je met je verjaardag.', true),
('bedanken', 'remercier', 'nl-fr', 'Ik bedank je voor je hulp.', true),
('vertellen', 'raconter', 'nl-fr', 'Ze vertelt een verhaal.', true),
('leren', 'apprendre', 'nl-fr', 'Ik leer Nederlands.', true),
('onderwijzen', 'enseigner', 'nl-fr', 'De leraar onderwijst wiskunde.', true),
('leven', 'vivre', 'nl-fr', 'We leven maar één keer.', true),
('sterven', 'mourir', 'nl-fr', 'De bloem sterft zonder water.', true),
('betalen', 'payer', 'nl-fr', 'Ik betaal de rekening.', true),
('kopen', 'acheter', 'nl-fr', 'Ik koop nieuwe schoenen.', true),
('verkopen', 'vendre', 'nl-fr', 'Ze verkoopt haar auto.', true),

-- Adjectives (60)
('groot', 'grand', 'nl-fr', 'Het huis is groot.', true),
('klein', 'petit', 'nl-fr', 'De hond is klein.', true),
('lang', 'long', 'nl-fr', 'De straat is lang.', true),
('kort', 'court', 'nl-fr', 'Het haar is kort.', true),
('dik', 'épais', 'nl-fr', 'Het boek is dik.', true),
('dun', 'mince', 'nl-fr', 'De muur is dun.', true),
('hoog', 'haut', 'nl-fr', 'De berg is hoog.', true),
('laag', 'bas', 'nl-fr', 'Het plafond is laag.', true),
('nieuw', 'nouveau', 'nl-fr', 'Ik heb een nieuwe auto.', true),
('oud', 'vieux', 'nl-fr', 'Het huis is oud.', true),
('jong', 'jeune', 'nl-fr', 'Ze is nog jong.', true),
('mooi', 'beau', 'nl-fr', 'Het landschap is mooi.', true),
('lelijk', 'laid', 'nl-fr', 'Het gebouw is lelijk.', true),
('schoon', 'propre', 'nl-fr', 'De kamer is schoon.', true),
('vies', 'sale', 'nl-fr', 'De vloer is vies.', true),
('goed', 'bon', 'nl-fr', 'Het eten is goed.', true),
('slecht', 'mauvais', 'nl-fr', 'Het weer is slecht vandaag.', true),
('leuk', 'sympa', 'nl-fr', 'Het feest was leuk.', true),
('saai', 'ennuyeux', 'nl-fr', 'De film was saai.', true),
('interessant', 'intéressant', 'nl-fr', 'Het boek is interessant.', true),
('gemakkelijk', 'facile', 'nl-fr', 'De toets was gemakkelijk.', true),
('moeilijk', 'difficile', 'nl-fr', 'De les is moeilijk.', true),
('snel', 'rapide', 'nl-fr', 'De trein is snel.', true),
('langzaam', 'lent', 'nl-fr', 'De schildpad is langzaam.', true),
('sterk', 'fort', 'nl-fr', 'Hij is erg sterk.', true),
('zwak', 'faible', 'nl-fr', 'Ze voelt zich zwak.', true),
('rijk', 'riche', 'nl-fr', 'Hij is erg rijk.', true),
('arm', 'pauvre', 'nl-fr', 'Ze is arm maar gelukkig.', true),
('gelukkig', 'heureux', 'nl-fr', 'Ze is gelukkig met haar leven.', true),
('droevig', 'triste', 'nl-fr', 'Hij is droevig om zijn verlies.', true),
('boos', 'en colère', 'nl-fr', 'Ze is boos op haar broer.', true),
('bang', 'effrayé', 'nl-fr', 'Het kind is bang in het donker.', true),
('moe', 'fatigué', 'nl-fr', 'Ik ben moe na het werk.', true),
('wakker', 'éveillé', 'nl-fr', 'Ben je al wakker?', true),
('gezond', 'sain', 'nl-fr', 'Groenten eten is gezond.', true),
('slim', 'intelligent', 'nl-fr', 'Ze is een slimme leerling.', true),
('grappig', 'drôle', 'nl-fr', 'De film is grappig.', true),
('rustig', 'calme', 'nl-fr', 'De tuin is rustig.', true),
('druk', 'occupé', 'nl-fr', 'Het centrum is druk.', true),
('vol', 'plein', 'nl-fr', 'De bus is vol.', true),
('leeg', 'vide', 'nl-fr', 'De fles is leeg.', true),
('open', 'ouvert', 'nl-fr', 'De deur is open.', true),
('gesloten', 'fermé', 'nl-fr', 'De winkel is gesloten.', true),
('hard', 'dur', 'nl-fr', 'Hij werkt hard.', true),
('zacht', 'doux', 'nl-fr', 'Het kussen is zacht.', true),
('vrolijk', 'joyeux', 'nl-fr', 'Ze is vrolijk vandaag.', true),
('verlegen', 'timide', 'nl-fr', 'Hij is verlegen bij vreemden.', true),
('lief', 'gentil', 'nl-fr', 'De baby is lief.', true),
('vriendelijk', 'aimable', 'nl-fr', 'De buren zijn vriendelijk.', true),
('gevaarlijk', 'dangereux', 'nl-fr', 'De weg is gevaarlijk bij mist.', true),
('veilig', 'sûr', 'nl-fr', 'Dit is een veilige buurt.', true),
('belangrijk', 'important', 'nl-fr', 'Dit is een belangrijk nieuws.', true),
('mogelijk', 'possible', 'nl-fr', 'Is het mogelijk om morgen te komen?', true),
('onmogelijk', 'impossible', 'nl-fr', 'Dat is onmogelijk.', true),
('juist', 'correct', 'nl-fr', 'Je antwoord is juist.', true),
('fout', 'faux', 'nl-fr', 'Je antwoord is fout.', true),
('populair', 'populaire', 'nl-fr', 'Hij is erg populair op school.', true),
('speciaal', 'spécial', 'nl-fr', 'Vandaag is een speciale dag.', true),
('normaal', 'normal', 'nl-fr', 'Dat is normaal.', true),
('lekker', 'délicieux', 'nl-fr', 'Het eten smaakt lekker.', true),
('vers', 'frais', 'nl-fr', 'Vers brood ruikt heerlijk.', true),

-- Adverbs/expressions (28)
('hier', 'ici', 'nl-fr', 'Kom hier, alsjeblieft.', true),
('daar', 'là-bas', 'nl-fr', 'De school is daar.', true),
('nu', 'maintenant', 'nl-fr', 'Kom nu naar huis.', true),
('later', 'plus tard', 'nl-fr', 'We praten later.', true),
('altijd', 'toujours', 'nl-fr', 'Ze is altijd op tijd.', true),
('nooit', 'jamais', 'nl-fr', 'Ik drink nooit alcohol.', true),
('vaak', 'souvent', 'nl-fr', 'Ik ga vaak naar de bioscoop.', true),
('soms', 'parfois', 'nl-fr', 'Soms eet ik buiten.', true),
('misschien', 'peut-être', 'nl-fr', 'Misschien kom ik morgen.', true),
('graag', 'avec plaisir', 'nl-fr', 'Ik help je graag.', true),
('heel', 'très', 'nl-fr', 'Het is heel warm vandaag.', true),
('erg', 'vraiment', 'nl-fr', 'Ik ben erg moe.', true),
('bijna', 'presque', 'nl-fr', 'Het is bijna klaar.', true),
('nog', 'encore', 'nl-fr', 'Slaap jij nog?', true),
('al', 'déjà', 'nl-fr', 'Ben je al klaar?', true),
('weer', 'de nouveau', 'nl-fr', 'Hij is weer laat.', true),
('ook', 'aussi', 'nl-fr', 'Ik wil ook meedoen.', true),
('alleen', 'seul', 'nl-fr', 'Ze woont alleen.', true),
('samen', 'ensemble', 'nl-fr', 'We doen het samen.', true),
('thuis', 'à la maison', 'nl-fr', 'Ik blijf thuis vandaag.', true),
('buiten', 'dehors', 'nl-fr', 'De kinderen spelen buiten.', true),
('binnen', 'dedans', 'nl-fr', 'Kom binnen, het regent.', true),
('eindelijk', 'enfin', 'nl-fr', 'Eindelijk is het weekend.', true),
('helaas', 'malheureusement', 'nl-fr', 'Helaas kan ik niet komen.', true),
('toevallig', 'par hasard', 'nl-fr', 'Toevallig zag ik hem in de winkel.', true),
('ongeveer', 'environ', 'nl-fr', 'Het kost ongeveer tien euro.', true),
('net', 'tout juste', 'nl-fr', 'Ik ben net aangekomen.', true),
('morgen', 'demain', 'nl-fr', 'We vertrekken morgen vroeg.', true),

-- Prepositions/conjunctions (20)
('in', 'dans', 'nl-fr', 'Ik woon in Amsterdam.', true),
('op', 'sur', 'nl-fr', 'Het boek ligt op de tafel.', true),
('aan', 'à', 'nl-fr', 'De lamp hangt aan het plafond.', true),
('bij', 'chez', 'nl-fr', 'Ik ben bij de supermarkt.', true),
('voor', 'avant', 'nl-fr', 'Ik sta voor de deur.', true),
('na', 'après', 'nl-fr', 'Na het eten gaan we wandelen.', true),
('met', 'avec', 'nl-fr', 'Ik ga met mijn vrienden.', true),
('zonder', 'sans', 'nl-fr', 'Ik ga zonder paraplu.', true),
('over', 'sur', 'nl-fr', 'We praten over het nieuws.', true),
('onder', 'sous', 'nl-fr', 'De kat zit onder de tafel.', true),
('tussen', 'entre', 'nl-fr', 'Het park ligt tussen de huizen.', true),
('naar', 'vers', 'nl-fr', 'We gaan naar het strand.', true),
('van', 'de', 'nl-fr', 'Dit is het huis van mijn oma.', true),
('tot', 'jusqu''à', 'nl-fr', 'Het museum is open tot vijf uur.', true),
('en', 'et', 'nl-fr', 'Ik drink thee en koffie.', true),
('maar', 'mais', 'nl-fr', 'Ik wil komen, maar ik kan niet.', true),
('of', 'ou', 'nl-fr', 'Wil je thee of koffie?', true),
('omdat', 'parce que', 'nl-fr', 'Ik blijf thuis omdat ik ziek ben.', true),
('als', 'si', 'nl-fr', 'Als het regent, blijf ik thuis.', true),
('dus', 'donc', 'nl-fr', 'Het is laat, dus ga ik slapen.', true),

-- Question words/pronouns (18)
('wie', 'qui', 'nl-fr', 'Wie is dat?', true),
('wat', 'quoi', 'nl-fr', 'Wat doe jij?', true),
('waar', 'où', 'nl-fr', 'Waar woon jij?', true),
('wanneer', 'quand', 'nl-fr', 'Wanneer kom je?', true),
('waarom', 'pourquoi', 'nl-fr', 'Waarom ben je laat?', true),
('hoe', 'comment', 'nl-fr', 'Hoe gaat het met jou?', true),
('welk', 'quel', 'nl-fr', 'Welk boek lees jij?', true),
('hoeveel', 'combien', 'nl-fr', 'Hoeveel kost dit?', true),
('ik', 'je', 'nl-fr', 'Ik heet Sara.', true),
('jij', 'tu', 'nl-fr', 'Jij bent mijn vriend.', true),
('hij', 'il', 'nl-fr', 'Hij is mijn broer.', true),
('zij', 'elle', 'nl-fr', 'Zij woont in Brussel.', true),
('wij', 'nous', 'nl-fr', 'Wij gaan samen op vakantie.', true),
('jullie', 'vous', 'nl-fr', 'Jullie zijn mijn beste vrienden.', true),
('mijn', 'mon', 'nl-fr', 'Dit is mijn huis.', true),
('iedereen', 'tout le monde', 'nl-fr', 'Iedereen is welkom.', true),
('niemand', 'personne', 'nl-fr', 'Niemand is er.', true),
('iets', 'quelque chose', 'nl-fr', 'Wil je iets drinken?', true),

-- Professions (30)
('de arts', 'le médecin', 'nl-fr', 'De arts onderzoekt de patiënt.', true),
('de apotheker', 'le pharmacien', 'nl-fr', 'De apotheker geeft me mijn medicijnen.', true),
('de professor', 'le professeur d''université', 'nl-fr', 'De professor geeft les aan de universiteit.', true),
('de advocaat', 'l''avocat', 'nl-fr', 'De advocaat verdedigt zijn cliënt.', true),
('de rechter', 'le juge', 'nl-fr', 'De rechter spreekt het vonnis uit.', true),
('de politieagent', 'le policier', 'nl-fr', 'De politieagent regelt het verkeer.', true),
('de brandweerman', 'le pompier', 'nl-fr', 'De brandweerman blust de brand.', true),
('de piloot', 'le pilote', 'nl-fr', 'De piloot landt het vliegtuig.', true),
('de kok', 'le cuisinier', 'nl-fr', 'De kok bereidt een heerlijk gerecht.', true),
('de kelner', 'le serveur', 'nl-fr', 'De kelner brengt het eten.', true),
('de bakker', 'le boulanger', 'nl-fr', 'De bakker bakt vers brood.', true),
('de slager', 'le boucher', 'nl-fr', 'De slager verkoopt vlees.', true),
('de boer', 'l''agriculteur', 'nl-fr', 'De boer werkt op het land.', true),
('de architect', 'l''architecte', 'nl-fr', 'De architect ontwerpt het gebouw.', true),
('de ingenieur', 'l''ingénieur', 'nl-fr', 'De ingenieur bouwt de brug.', true),
('de journalist', 'le journaliste', 'nl-fr', 'De journalist schrijft het artikel.', true),
('de fotograaf', 'le photographe', 'nl-fr', 'De fotograaf maakt mooie foto''s.', true),
('de acteur', 'l''acteur', 'nl-fr', 'De acteur speelt in een film.', true),
('de schrijver', 'l''écrivain', 'nl-fr', 'De schrijver schrijft een roman.', true),
('de vertaler', 'le traducteur', 'nl-fr', 'De vertaler vertaalt het document.', true),
('de chauffeur', 'le chauffeur', 'nl-fr', 'De chauffeur rijdt de bus.', true),
('de directeur', 'le directeur', 'nl-fr', 'De directeur leidt het bedrijf.', true),
('de secretaresse', 'la secrétaire', 'nl-fr', 'De secretaresse beheert de agenda.', true),
('de accountant', 'le comptable', 'nl-fr', 'De accountant controleert de cijfers.', true),
('de psycholoog', 'le psychologue', 'nl-fr', 'De psycholoog helpt zijn patiënten.', true),
('de verpleegster', 'l''infirmière', 'nl-fr', 'De verpleegster zorgt voor de zieken.', true),
('de steward', 'le steward', 'nl-fr', 'De steward helpt passagiers in het vliegtuig.', true),
('de wetenschapper', 'le scientifique', 'nl-fr', 'De wetenschapper doet onderzoek.', true),
('de ontwerper', 'le designer', 'nl-fr', 'De ontwerper maakt een nieuwe collectie.', true),
('de ondernemer', 'l''entrepreneur', 'nl-fr', 'De ondernemer start een nieuw bedrijf.', true),

-- Places/city (28)
('de stad', 'la ville', 'nl-fr', 'Amsterdam is een mooie stad.', true),
('de bioscoop', 'le cinéma', 'nl-fr', 'We gaan naar de bioscoop.', true),
('de camping', 'le camping', 'nl-fr', 'We slapen op de camping.', true),
('de kerk', 'l''église', 'nl-fr', 'De kerk is oud en mooi.', true),
('de ambassade', 'l''ambassade', 'nl-fr', 'Ik haal mijn visum bij de ambassade.', true),
('de speeltuin', 'l''aire de jeux', 'nl-fr', 'De kinderen spelen in de speeltuin.', true),
('de bar', 'le bar', 'nl-fr', 'We drinken een biertje in de bar.', true),
('de buurt', 'le quartier', 'nl-fr', 'We wonen in een rustige buurt.', true),
('de grens', 'la frontière', 'nl-fr', 'We rijden over de grens naar België.', true),
('de hoofdstad', 'la capitale', 'nl-fr', 'Amsterdam is de hoofdstad van Nederland.', true),
('de kaart', 'la carte', 'nl-fr', 'Ik bekijk de kaart.', true),
('de richting', 'la direction', 'nl-fr', 'In welke richting is het station?', true),
('de ingang', 'l''entrée', 'nl-fr', 'De ingang is aan de voorzijde.', true),
('de uitgang', 'la sortie', 'nl-fr', 'De uitgang is aan de achterkant.', true),
('de parking', 'le parking', 'nl-fr', 'Ik parkeer in de parking.', true),
('het dorp', 'le village', 'nl-fr', 'Ze woont in een klein dorp.', true),
('het centrum', 'le centre-ville', 'nl-fr', 'We winkelen in het centrum.', true),
('het buitenland', 'l''étranger', 'nl-fr', 'Ze woont in het buitenland.', true),
('het museum', 'le musée', 'nl-fr', 'We bezoeken het museum.', true),
('het theater', 'le théâtre', 'nl-fr', 'We gaan naar het theater.', true),
('het stadion', 'le stade', 'nl-fr', 'Het stadion is vol bij de wedstrijd.', true),
('het hotel', 'l''hôtel', 'nl-fr', 'We overnachten in een hotel.', true),
('het café', 'le café', 'nl-fr', 'We zitten in het café.', true),
('het restaurant', 'le restaurant', 'nl-fr', 'We eten in een restaurant.', true),
('de bakkerij', 'la boulangerie', 'nl-fr', 'Ik koop vers brood bij de bakkerij.', true),
('het postkantoor', 'la poste', 'nl-fr', 'Ik stuur een pakket via het postkantoor.', true),
('de sporthal', 'la salle de sport', 'nl-fr', 'We sporten in de sporthal.', true),
('de dierentuin', 'le zoo', 'nl-fr', 'We bezoeken de dierentuin met de kinderen.', true),

-- Emotions (20)
('de liefde', 'l''amour', 'nl-fr', 'De liefde voor haar familie is groot.', true),
('de vreugde', 'la joie', 'nl-fr', 'De vreugde op haar gezicht was zichtbaar.', true),
('de angst', 'la peur', 'nl-fr', 'De angst voor spinnen is groot.', true),
('de boosheid', 'la colère', 'nl-fr', 'Zijn boosheid was goed te zien.', true),
('de verrassing', 'la surprise', 'nl-fr', 'De verrassing maakte haar gelukkig.', true),
('de jaloezie', 'la jalousie', 'nl-fr', 'Jaloezie is niet goed.', true),
('de trots', 'la fierté', 'nl-fr', 'De trots van de ouders was zichtbaar.', true),
('de hoop', 'l''espoir', 'nl-fr', 'De hoop geeft kracht.', true),
('de teleurstelling', 'la déception', 'nl-fr', 'De teleurstelling was groot na de verlies.', true),
('de opluchting', 'le soulagement', 'nl-fr', 'De opluchting na het examen was groot.', true),
('de eenzaamheid', 'la solitude', 'nl-fr', 'Eenzaamheid is moeilijk te dragen.', true),
('de emotie', 'l''émotion', 'nl-fr', 'Ze toonde veel emotie.', true),
('de bewondering', 'l''admiration', 'nl-fr', 'Haar bewondering voor hem groeide.', true),
('de schaamte', 'la honte', 'nl-fr', 'Hij voelde schaamte voor zijn fout.', true),
('de nostalgie', 'la nostalgie', 'nl-fr', 'De nostalgie naar zijn geboorteland was groot.', true),
('de wanhoop', 'le désespoir', 'nl-fr', 'De wanhoop maakte hem stil.', true),
('het verdriet', 'la tristesse', 'nl-fr', 'Het verdriet om zijn verlies was groot.', true),
('het enthousiasme', 'l''enthousiasme', 'nl-fr', 'Haar enthousiasme is aanstekelijk.', true),
('het geluk', 'le bonheur', 'nl-fr', 'Het geluk in haar ogen was duidelijk.', true),
('de voldoening', 'la satisfaction', 'nl-fr', 'De voldoening na het werk is groot.', true),

-- Dutch specialty foods (20)
('de stroopwafel', 'la gaufre au sirop', 'nl-fr', 'Een stroopwafel op je koffie is heerlijk.', true),
('de drop', 'la réglisse', 'nl-fr', 'Drop is typisch Nederlands snoep.', true),
('de poffertjes', 'les mini-crêpes hollandaises', 'nl-fr', 'Poffertjes eet je met boter en suiker.', true),
('de bitterballen', 'les boulettes frites hollandaises', 'nl-fr', 'Bitterballen zijn lekker als borrelsnack.', true),
('de stamppot', 'le stamppot', 'nl-fr', 'Stamppot met worst is typisch Nederlands.', true),
('de erwtensoep', 'la soupe aux pois', 'nl-fr', 'Erwtensoep eten we in de winter.', true),
('de haring', 'le hareng', 'nl-fr', 'Haring met ui is een Nederlandse delicatesse.', true),
('de speculaas', 'les spéculoos', 'nl-fr', 'Speculaas eet je met Sinterklaas.', true),
('de ontbijtkoek', 'le pain d''épices', 'nl-fr', 'Ontbijtkoek eet je bij het ontbijt.', true),
('de vla', 'la crème anglaise', 'nl-fr', 'Vla is een Hollands toetje.', true),
('de appelflap', 'le chausson aux pommes', 'nl-fr', 'Een appelflap is een lekker gebakje.', true),
('de kroket', 'la croquette', 'nl-fr', 'Een kroket uit de muur is typisch Nederlands.', true),
('de frikandel', 'le frikandel', 'nl-fr', 'Een frikandel is een snackbar klassieker.', true),
('de oliebollen', 'les beignets hollandais', 'nl-fr', 'Op oudejaarsavond eten we oliebollen.', true),
('de hagelslag', 'les vermicelles au chocolat', 'nl-fr', 'Hagelslag op brood is typisch Nederlands.', true),
('de pindakaas', 'le beurre de cacahuète', 'nl-fr', 'Pindakaas op brood is een klassiek ontbijt.', true),
('de rookworst', 'la saucisse fumée', 'nl-fr', 'Rookworst is lekker in de stamppot.', true),
('de boerenkool', 'le chou frisé', 'nl-fr', 'Boerenkool is gezond en lekker.', true),
('de wentelteefjes', 'le pain perdu hollandais', 'nl-fr', 'Wentelteefjes eet je als ontbijt.', true),
('de gevulde koek', 'le biscuit à la pâte d''amande', 'nl-fr', 'Een gevulde koek smaakt naar amandelspijs.', true),

-- Abstract nouns (35)
('de tijd', 'le temps', 'nl-fr', 'De tijd vliegt als je plezier hebt.', true),
('de ruimte', 'l''espace', 'nl-fr', 'Er is geen ruimte meer.', true),
('de energie', 'l''énergie', 'nl-fr', 'Ik heb geen energie vandaag.', true),
('de kracht', 'la force', 'nl-fr', 'Hij heeft veel kracht.', true),
('de vrijheid', 'la liberté', 'nl-fr', 'Vrijheid is kostbaar.', true),
('de vrede', 'la paix', 'nl-fr', 'We hopen op vrede.', true),
('de oplossing', 'la solution', 'nl-fr', 'We zoeken een oplossing.', true),
('de cultuur', 'la culture', 'nl-fr', 'Elke cultuur is uniek.', true),
('de traditie', 'la tradition', 'nl-fr', 'Dit is een oude traditie.', true),
('de waarde', 'la valeur', 'nl-fr', 'Eerlijkheid is een belangrijke waarde.', true),
('de betekenis', 'la signification', 'nl-fr', 'Wat is de betekenis van dit woord?', true),
('de toekomst', 'l''avenir', 'nl-fr', 'We denken aan de toekomst.', true),
('de vraag', 'la question', 'nl-fr', 'Ik heb een vraag voor jou.', true),
('de informatie', 'l''information', 'nl-fr', 'Ik heb meer informatie nodig.', true),
('de kans', 'l''opportunité', 'nl-fr', 'Dit is een goede kans voor jou.', true),
('de ervaring', 'l''expérience', 'nl-fr', 'Ze heeft veel ervaring.', true),
('de kennis', 'le savoir', 'nl-fr', 'Kennis is macht.', true),
('de mening', 'l''opinion', 'nl-fr', 'Wat is jouw mening?', true),
('de reden', 'la raison', 'nl-fr', 'Wat is de reden voor je vertraging?', true),
('de overeenkomst', 'l''accord', 'nl-fr', 'We sluiten een overeenkomst.', true),
('de regel', 'la règle', 'nl-fr', 'Volg de regels.', true),
('de wet', 'la loi', 'nl-fr', 'We moeten de wet volgen.', true),
('de verantwoordelijkheid', 'la responsabilité', 'nl-fr', 'Dat is mijn verantwoordelijkheid.', true),
('de mogelijkheid', 'la possibilité', 'nl-fr', 'Er zijn veel mogelijkheden.', true),
('de kwaliteit', 'la qualité', 'nl-fr', 'De kwaliteit van dit product is goed.', true),
('het idee', 'l''idée', 'nl-fr', 'Dat is een goed idee.', true),
('het plan', 'le plan', 'nl-fr', 'Wat is je plan voor morgen?', true),
('het doel', 'l''objectif', 'nl-fr', 'Mijn doel is om gezond te leven.', true),
('het succes', 'le succès', 'nl-fr', 'Succes met je examen!', true),
('het probleem', 'le problème', 'nl-fr', 'Wat is het probleem?', true),
('het nieuws', 'les nouvelles', 'nl-fr', 'Ik lees het nieuws elke ochtend.', true),
('het verhaal', 'le récit', 'nl-fr', 'Ze vertelt een mooi verhaal.', true),
('het bericht', 'le message', 'nl-fr', 'Ik stuur je een bericht.', true),
('het gevoel', 'le sentiment', 'nl-fr', 'Ik heb een goed gevoel hierover.', true),
('het verschil', 'la différence', 'nl-fr', 'Wat is het verschil?', true),
('het risico', 'le risque', 'nl-fr', 'Er is een risico verbonden aan dit plan.', true),
('het gevolg', 'la conséquence', 'nl-fr', 'Wat zijn de gevolgen?', true),
('het antwoord', 'la réponse', 'nl-fr', 'Ik weet het antwoord niet.', true),

-- Greetings/expressions (26)
('hallo', 'salut', 'nl-fr', 'Hallo, hoe gaat het?', true),
('goedemorgen', 'bonjour (matin)', 'nl-fr', 'Goedemorgen, heb je goed geslapen?', true),
('goedemiddag', 'bonjour (après-midi)', 'nl-fr', 'Goedemiddag, kan ik je helpen?', true),
('goedenavond', 'bonsoir', 'nl-fr', 'Goedenavond, welkom thuis.', true),
('goedenacht', 'bonne nuit', 'nl-fr', 'Goedenacht, slaap lekker.', true),
('dag', 'bonjour / au revoir', 'nl-fr', 'Dag, tot morgen!', true),
('tot ziens', 'au revoir', 'nl-fr', 'Tot ziens, het was leuk!', true),
('tot morgen', 'à demain', 'nl-fr', 'Tot morgen, slaap lekker.', true),
('alsjeblieft', 's''il te plaît', 'nl-fr', 'Kun je me helpen, alsjeblieft?', true),
('dank je', 'merci', 'nl-fr', 'Dank je voor je hulp.', true),
('dank u wel', 'merci beaucoup', 'nl-fr', 'Dank u wel voor uw medewerking.', true),
('graag gedaan', 'de rien', 'nl-fr', 'Graag gedaan, geen probleem.', true),
('sorry', 'désolé', 'nl-fr', 'Sorry, dat was mijn fout.', true),
('excuseer', 'excusez-moi', 'nl-fr', 'Excuseer, mag ik erdoor?', true),
('ja', 'oui', 'nl-fr', 'Ja, dat klopt.', true),
('nee', 'non', 'nl-fr', 'Nee, dat wil ik niet.', true),
('prima', 'parfait', 'nl-fr', 'Prima, dan spreken we af.', true),
('niet zo goed', 'pas très bien', 'nl-fr', 'Het gaat niet zo goed vandaag.', true),
('gefeliciteerd', 'félicitations', 'nl-fr', 'Gefeliciteerd met je verjaardag!', true),
('proficiat', 'bravo', 'nl-fr', 'Proficiat met je diploma!', true),
('veel succes', 'bonne chance', 'nl-fr', 'Veel succes met je examen!', true),
('beterschap', 'bon rétablissement', 'nl-fr', 'Beterschap, ik hoop dat je snel beter bent.', true),
('smakelijk', 'bon appétit', 'nl-fr', 'Smakelijk eten!', true),
('proost', 'santé', 'nl-fr', 'Proost op ons succes!', true),
('welkom', 'bienvenue', 'nl-fr', 'Welkom in ons huis!', true),
('tot later', 'à tout à l''heure', 'nl-fr', 'Tot later, tot vanavond!', true),

-- Extra verbs (10)
('tekenen', 'dessiner', 'nl-fr', 'De kinderen tekenen in de klas.', true),
('schilderen', 'peindre', 'nl-fr', 'Hij schildert een portret.', true),
('praten', 'parler / discuter', 'nl-fr', 'We praten over het weekend.', true),
('roepen', 'appeler / crier', 'nl-fr', 'Ze roept zijn naam.', true),
('pakken', 'prendre / attraper', 'nl-fr', 'Pak de bal!', true),
('zetten', 'mettre / poser', 'nl-fr', 'Zet de tas op de grond.', true),
('leggen', 'poser / placer', 'nl-fr', 'Leg het boek op de tafel.', true),
('hangen', 'accrocher / être suspendu', 'nl-fr', 'De jas hangt aan de kapstok.', true),
('vallen', 'tomber', 'nl-fr', 'Het kind valt van de fiets.', true),
('stijgen', 'monter / augmenter', 'nl-fr', 'De prijzen stijgen elk jaar.', true),

-- Extra adjectives (10)
('tevreden', 'satisfait / content', 'nl-fr', 'Ze is tevreden met haar resultaat.', true),
('ontevreden', 'insatisfait / mécontent', 'nl-fr', 'Hij is ontevreden met zijn baan.', true),
('zeker', 'sûr / certain', 'nl-fr', 'Ik ben zeker van mijn antwoord.', true),
('onzeker', 'incertain / hésitant', 'nl-fr', 'Ze voelt zich onzeker.', true),
('eerlijk', 'honnête', 'nl-fr', 'Hij is altijd eerlijk.', true),
('oneerlijk', 'malhonnête', 'nl-fr', 'Dat is oneerlijk.', true),
('dapper', 'courageux', 'nl-fr', 'De brandweerman is dapper.', true),
('lui', 'paresseux', 'nl-fr', 'Hij is lui en werkt niet hard.', true),
('netjes', 'soigné / ordonné', 'nl-fr', 'Haar kamer is netjes.', true),
('rommelig', 'désordonné', 'nl-fr', 'Zijn bureau is rommelig.', true),

-- Extra nouns - house/daily life (15)
('de tuin', 'le jardin', 'nl-fr', 'We zitten in de tuin.', true),
('de schuur', 'la grange / la remise', 'nl-fr', 'De fiets staat in de schuur.', true),
('de plantenpot', 'le pot de fleurs', 'nl-fr', 'De bloem staat in een plantenpot.', true),
('de kaars', 'la bougie', 'nl-fr', 'We steken kaarsen aan bij het diner.', true),
('de klok', 'l''horloge', 'nl-fr', 'De klok aan de muur loopt gelijk.', true),
('het schilderij', 'le tableau', 'nl-fr', 'Het schilderij hangt aan de muur.', true),
('de vaat', 'la vaisselle', 'nl-fr', 'Ik doe de vaat na het eten.', true),
('de kapstok', 'le porte-manteau', 'nl-fr', 'Hang je jas aan de kapstok.', true),
('de vuilnisbak', 'la poubelle', 'nl-fr', 'Gooi het afval in de vuilnisbak.', true),
('de wastafel', 'le lavabo', 'nl-fr', 'Was je handen bij de wastafel.', true),
('het plank', 'l''étagère / la planche', 'nl-fr', 'De boeken staan op het plank.', true),
('de wekker', 'le réveil', 'nl-fr', 'Mijn wekker gaat om zeven uur.', true),
('de stofzuiger', 'l''aspirateur', 'nl-fr', 'Ik gebruik de stofzuiger om het tapijt schoon te maken.', true),
('de kraan', 'le robinet', 'nl-fr', 'Draai de kraan dicht.', true),
('de mat', 'le tapis de sol / le paillasson', 'nl-fr', 'Veeg je voeten op de mat.', true),

-- Extra food/nature (10)
('de broccoli', 'le brocoli', 'nl-fr', 'Broccoli is gezond en groen.', true),
('de bloemkool', 'le chou-fleur', 'nl-fr', 'Bloemkool is wit en lekker.', true),
('de bosbes', 'la myrtille', 'nl-fr', 'Bosbessen zijn paars en zoet.', true),
('de mango', 'la mangue', 'nl-fr', 'Mango is een tropisch fruit.', true),
('de ananas', 'l''ananas', 'nl-fr', 'Ananas is zoet en zuur.', true),
('de avocado', 'l''avocat', 'nl-fr', 'Avocado is lekker op brood.', true),
('de walnoot', 'la noix', 'nl-fr', 'Walnoten zijn gezond.', true),
('de amandel', 'l''amande', 'nl-fr', 'Amandelen zijn lekker als snack.', true),
('de honing', 'le miel', 'nl-fr', 'Honing is zoet en lekker in thee.', true),
('de jam', 'la confiture', 'nl-fr', 'Ik smeer jam op mijn brood.', true),

-- Extra society/abstract (10)
('de overheid', 'le gouvernement', 'nl-fr', 'De overheid maakt de regels.', true),
('de politiek', 'la politique', 'nl-fr', 'Hij interesseert zich voor politiek.', true),
('de economie', 'l''économie', 'nl-fr', 'De economie groeit dit jaar.', true),
('de maatschappij', 'la société', 'nl-fr', 'Iedereen maakt deel uit van de maatschappij.', true),
('de democratie', 'la démocratie', 'nl-fr', 'Nederland is een democratie.', true),
('de solidariteit', 'la solidarité', 'nl-fr', 'Solidariteit is belangrijk in moeilijke tijden.', true),
('de gelijkheid', 'l''égalité', 'nl-fr', 'Gelijkheid voor iedereen is een recht.', true),
('de duurzaamheid', 'la durabilité', 'nl-fr', 'Duurzaamheid is belangrijk voor het milieu.', true),
('de innovatie', 'l''innovation', 'nl-fr', 'Innovatie drijft de economie vooruit.', true),
('de communicatie', 'la communication', 'nl-fr', 'Goede communicatie is essentieel.', true),

-- Extra body/health (5)
('de enkel', 'la cheville', 'nl-fr', 'Ze heeft haar enkel verzwikt.', true),
('de pols', 'le poignet', 'nl-fr', 'Zijn pols is gebroken.', true),
('de kaak', 'la mâchoire', 'nl-fr', 'Mijn kaak doet pijn.', true),
('de wenkbrauw', 'le sourcil', 'nl-fr', 'Hij fronst zijn wenkbrauwen.', true),
('de lip', 'la lèvre', 'nl-fr', 'Ze heeft rode lippen.', true),

-- Extra weather/nature (4)
('de regenboog', 'l''arc-en-ciel', 'nl-fr', 'Na de regen zien we een regenboog.', true),
('de dew', 'la rosée', 'nl-fr', 'Er ligt dauw op het gras.', true),
('de vorst', 'le gel', 'nl-fr', 'Bij vorst is het glad.', true),
('de nevel', 'la brume', 'nl-fr', 'Er hangt nevel boven het meer.', true),

-- Extra to reach 1000 (10)
('de paraplu', 'le parapluie', 'nl-fr', 'Neem een paraplu mee, het gaat regenen.', true),
('de zonnebril', 'les lunettes de soleil', 'nl-fr', 'Ze draagt een zonnebril in de zon.', true),
('de bril', 'les lunettes', 'nl-fr', 'Hij draagt een bril om beter te zien.', true),
('de agenda', 'l''agenda', 'nl-fr', 'Ik schrijf de vergadering in mijn agenda.', true),
('de kalender', 'le calendrier', 'nl-fr', 'Ik bekijk de kalender voor de datum.', true),
('het cadeau', 'le cadeau', 'nl-fr', 'Ik geef haar een cadeau voor haar verjaardag.', true),
('de verjaardag', 'l''anniversaire', 'nl-fr', 'Vandaag is mijn verjaardag.', true),
('het feest', 'la fête', 'nl-fr', 'We organiseren een feest.', true),
('de uitnodiging', 'l''invitation', 'nl-fr', 'Ik stuur een uitnodiging voor het feest.', true),
('de herinnering', 'le souvenir', 'nl-fr', 'Dit object is een mooie herinnering.', true)
;
