-- 1000 mots néerlandais de base pour Knowledge Quiz
-- language_pair: nl-fr | Exécuter dans Supabase SQL Editor

INSERT INTO vocabulary (source_word, target_translation, language_pair, example_sentence) VALUES

-- CHIFFRES & NOMBRES (25)
('één', 'un / une', 'nl-fr', 'Ik heb één broer.'),
('twee', 'deux', 'nl-fr', 'Ik heb twee katten.'),
('drie', 'trois', 'nl-fr', 'Er zijn drie stoelen.'),
('vier', 'vier', 'nl-fr', 'De tafel heeft vier poten.'),
('vijf', 'cinq', 'nl-fr', 'Ik eet vijf appels per week.'),
('zes', 'six', 'nl-fr', 'Ze werkt zes uur per dag.'),
('zeven', 'sept', 'nl-fr', 'Een week heeft zeven dagen.'),
('acht', 'huit', 'nl-fr', 'Ik slaap acht uur.'),
('negen', 'neuf', 'nl-fr', 'De trein vertrekt om negen uur.'),
('tien', 'dix', 'nl-fr', 'Ik heb tien vingers.'),
('elf', 'onze', 'nl-fr', 'Het spel begint om elf uur.'),
('twaalf', 'douze', 'nl-fr', 'Een jaar heeft twaalf maanden.'),
('twintig', 'vingt', 'nl-fr', 'Hij is twintig jaar oud.'),
('dertig', 'trente', 'nl-fr', 'Ze heeft dertig euro nodig.'),
('veertig', 'quarante', 'nl-fr', 'De auto rijdt veertig kilometer per uur.'),
('vijftig', 'cinquante', 'nl-fr', 'Het boek kost vijftig euro.'),
('honderd', 'cent', 'nl-fr', 'Er zijn honderd mensen in de zaal.'),
('duizend', 'mille', 'nl-fr', 'De stad heeft duizend inwoners.'),
('nul', 'zéro', 'nl-fr', 'De temperatuur is nul graden.'),
('eerste', 'premier / première', 'nl-fr', 'Vandaag is de eerste dag van het jaar.'),
('tweede', 'deuxième', 'nl-fr', 'Hij woont op de tweede verdieping.'),
('half', 'demi / à moitié', 'nl-fr', 'Ik wil een half brood.'),
('kwart', 'quart', 'nl-fr', 'Het is kwart over drie.'),
('miljoen', 'million', 'nl-fr', 'De stad heeft een miljoen inwoners.'),
('getal', 'nombre / chiffre', 'nl-fr', 'Noem een getal tussen één en tien.'),

-- JOURS & MOIS (19)
('maandag', 'lundi', 'nl-fr', 'Op maandag ga ik naar school.'),
('dinsdag', 'mardi', 'nl-fr', 'Dinsdag heb ik een vergadering.'),
('woensdag', 'mercredi', 'nl-fr', 'Woensdag is het midden van de week.'),
('donderdag', 'jeudi', 'nl-fr', 'Op donderdag doe ik boodschappen.'),
('vrijdag', 'vendredi', 'nl-fr', 'Vrijdag is mijn favoriete dag.'),
('zaterdag', 'samedi', 'nl-fr', 'Op zaterdag slaap ik uit.'),
('zondag', 'dimanche', 'nl-fr', 'We eten samen op zondag.'),
('januari', 'janvier', 'nl-fr', 'Het is koud in januari.'),
('februari', 'février', 'nl-fr', 'Februari heeft achtentwintig dagen.'),
('maart', 'mars', 'nl-fr', 'In maart begint de lente.'),
('april', 'avril', 'nl-fr', 'Het regent vaak in april.'),
('mei', 'mai', 'nl-fr', 'De bloemen bloeien in mei.'),
('juni', 'juin', 'nl-fr', 'In juni eindigt het schooljaar.'),
('juli', 'juillet', 'nl-fr', 'We gaan op vakantie in juli.'),
('augustus', 'août', 'nl-fr', 'Augustus is de warmste maand.'),
('september', 'septembre', 'nl-fr', 'In september begint school weer.'),
('oktober', 'octobre', 'nl-fr', 'De bladeren vallen in oktober.'),
('november', 'novembre', 'nl-fr', 'Het is bewolkt in november.'),
('december', 'décembre', 'nl-fr', 'Kerstmis is in december.'),

-- TEMPS & DURÉE (12)
('dag', 'jour', 'nl-fr', 'Het is een mooie dag.'),
('week', 'semaine', 'nl-fr', 'Deze week werk ik hard.'),
('maand', 'mois', 'nl-fr', 'Volgende maand ga ik op reis.'),
('jaar', 'année / an', 'nl-fr', 'Dit jaar leer ik Nederlands.'),
('uur', 'heure', 'nl-fr', 'Het is twee uur.'),
('minuut', 'minute', 'nl-fr', 'De trein vertrekt over vijf minuten.'),
('seconde', 'seconde', 'nl-fr', 'Wacht een seconde.'),
('ochtend', 'matin', 'nl-fr', 'Ik drink koffie in de ochtend.'),
('middag', 'après-midi / midi', 'nl-fr', 'We eten brood s middags.'),
('avond', 'soir', 'nl-fr', 'Goede avond! Hoe gaat het?'),
('nacht', 'nuit', 'nl-fr', 'Ik slaap goed deze nacht.'),
('gisteren', 'hier', 'nl-fr', 'Gisteren was een mooie dag.'),

-- MÉTÉO & SAISONS (20)
('lente', 'printemps', 'nl-fr', 'In de lente bloeien de bloemen.'),
('zomer', 'été', 'nl-fr', 'In de zomer gaan we naar het strand.'),
('herfst', 'automne', 'nl-fr', 'In de herfst vallen de bladeren.'),
('winter', 'hiver', 'nl-fr', 'In de winter sneeuwt het soms.'),
('regen', 'pluie', 'nl-fr', 'Er valt veel regen in Nederland.'),
('zon', 'soleil', 'nl-fr', 'De zon schijnt vandaag.'),
('wind', 'vent', 'nl-fr', 'Er staat veel wind aan zee.'),
('sneeuw', 'neige', 'nl-fr', 'De kinderen spelen in de sneeuw.'),
('wolk', 'nuage', 'nl-fr', 'Er zijn veel wolken vandaag.'),
('onweer', 'orage', 'nl-fr', 'Er komt een onweer aan.'),
('mist', 'brouillard', 'nl-fr', 'Er is dichte mist op de weg.'),
('storm', 'tempête', 'nl-fr', 'Er is een grote storm op zee.'),
('bliksem', 'éclair', 'nl-fr', 'De bliksem verlicht de hemel.'),
('donder', 'tonnerre', 'nl-fr', 'Ik hoor de donder in de verte.'),
('hagel', 'grêle', 'nl-fr', 'Het hagelt heel hard vandaag.'),
('temperatuur', 'température', 'nl-fr', 'De temperatuur is tien graden.'),
('weerbericht', 'bulletin météo', 'nl-fr', 'Ik kijk elke ochtend naar het weerbericht.'),
('lucht', 'air / ciel', 'nl-fr', 'De lucht is helder en blauw.'),
('ijzel', 'verglas', 'nl-fr', 'Wees voorzichtig, er is ijzel op de weg.'),
('droogte', 'sécheresse', 'nl-fr', 'Er is droogte in het zuiden.'),

-- COULEURS (15)
('rood', 'rouge', 'nl-fr', 'De roos is rood.'),
('blauw', 'bleu', 'nl-fr', 'De lucht is blauw.'),
('groen', 'vert', 'nl-fr', 'Het gras is groen.'),
('geel', 'jaune', 'nl-fr', 'De zon is geel.'),
('zwart', 'noir', 'nl-fr', 'De nacht is zwart.'),
('wit', 'blanc', 'nl-fr', 'De sneeuw is wit.'),
('grijs', 'gris', 'nl-fr', 'De lucht is grijs vandaag.'),
('oranje', 'orange', 'nl-fr', 'De sinaasappel is oranje.'),
('roze', 'rose', 'nl-fr', 'Ze draagt een roze jurk.'),
('paars', 'violet', 'nl-fr', 'De lavendel is paars.'),
('bruin', 'marron / brun', 'nl-fr', 'De chocolade is bruin.'),
('beige', 'beige', 'nl-fr', 'Ze heeft een beige jas aan.'),
('goud', 'or / doré', 'nl-fr', 'De ring is van goud.'),
('zilver', 'argent / argenté', 'nl-fr', 'De munt is van zilver.'),
('kleur', 'couleur', 'nl-fr', 'Wat is je favoriete kleur?'),

-- PARTIES DU CORPS (30)
('hoofd', 'tête', 'nl-fr', 'Ik heb pijn in mijn hoofd.'),
('haar', 'cheveux', 'nl-fr', 'Ze heeft lang haar.'),
('oog', 'œil', 'nl-fr', 'Hij heeft blauwe ogen.'),
('oor', 'oreille', 'nl-fr', 'Praat in mijn oor.'),
('neus', 'nez', 'nl-fr', 'Mijn neus is rood van de kou.'),
('mond', 'bouche', 'nl-fr', 'Open je mond bij de dokter.'),
('tand', 'dent', 'nl-fr', 'Ik poets elke dag mijn tanden.'),
('tong', 'langue', 'nl-fr', 'De tong helpt ons spreken en proeven.'),
('keel', 'gorge', 'nl-fr', 'Ik heb keelpijn vandaag.'),
('nek', 'cou / nuque', 'nl-fr', 'Mijn nek doet pijn na het slapen.'),
('schouder', 'épaule', 'nl-fr', 'Hij draagt een tas op zijn schouder.'),
('arm', 'bras', 'nl-fr', 'Ze heeft sterke armen.'),
('elleboog', 'coude', 'nl-fr', 'Ik stoot mijn elleboog tegen de tafel.'),
('hand', 'main', 'nl-fr', 'Geef me een hand!'),
('vinger', 'doigt', 'nl-fr', 'Ik heb vijf vingers aan elke hand.'),
('borst', 'poitrine', 'nl-fr', 'Hij heeft pijn op zijn borst.'),
('buik', 'ventre / abdomen', 'nl-fr', 'Mijn buik knort van de honger.'),
('rug', 'dos', 'nl-fr', 'Mijn rug doet pijn van het zitten.'),
('been', 'jambe', 'nl-fr', 'Hij heeft zijn been gebroken.'),
('knie', 'genou', 'nl-fr', 'Mijn knie doet pijn na het lopen.'),
('voet', 'pied', 'nl-fr', 'Mijn voeten zijn moe.'),
('teen', 'orteil', 'nl-fr', 'Ik stoot mijn teen aan de deur.'),
('huid', 'peau', 'nl-fr', 'De huid beschermt ons lichaam.'),
('hart', 'cœur', 'nl-fr', 'Mijn hart klopt snel.'),
('long', 'poumon', 'nl-fr', 'We ademen met onze longen.'),
('maag', 'estomac', 'nl-fr', 'Mijn maag doet pijn.'),
('hersenen', 'cerveau', 'nl-fr', 'De hersenen zijn het controlesysteem van het lichaam.'),
('bloed', 'sang', 'nl-fr', 'Het bloed stroomt door het lichaam.'),
('bot', 'os', 'nl-fr', 'Een bot is het harde deel van het lichaam.'),
('spier', 'muscle', 'nl-fr', 'Sporten maakt je spieren sterker.'),

-- FAMILLE & PERSONNES (28)
('moeder', 'mère', 'nl-fr', 'Mijn moeder kookt lekker.'),
('vader', 'père', 'nl-fr', 'Mijn vader werkt als dokter.'),
('broer', 'frère', 'nl-fr', 'Mijn broer is twee jaar ouder dan ik.'),
('zus', 'sœur', 'nl-fr', 'Mijn zus studeert in Amsterdam.'),
('grootmoeder', 'grand-mère', 'nl-fr', 'Mijn grootmoeder bakt heerlijke koekjes.'),
('grootvader', 'grand-père', 'nl-fr', 'Mijn grootvader vertelt goede verhalen.'),
('oom', 'oncle', 'nl-fr', 'Mijn oom woont in Rotterdam.'),
('tante', 'tante', 'nl-fr', 'Mijn tante heeft drie kinderen.'),
('neef', 'cousin / neveu', 'nl-fr', 'Mijn neef is acht jaar oud.'),
('nicht', 'cousine / nièce', 'nl-fr', 'Mijn nicht speelt viool.'),
('kind', 'enfant', 'nl-fr', 'Het kind speelt in de tuin.'),
('baby', 'bébé', 'nl-fr', 'De baby huilt vannacht.'),
('man', 'homme / mari', 'nl-fr', 'Haar man is een goede kok.'),
('vrouw', 'femme / épouse', 'nl-fr', 'Zijn vrouw werkt als lerares.'),
('jongen', 'garçon', 'nl-fr', 'De jongen speelt voetbal.'),
('meisje', 'fille / jeune fille', 'nl-fr', 'Het meisje danst heel goed.'),
('vriend', 'ami / petit ami', 'nl-fr', 'Mijn vriend heet Thomas.'),
('vriendin', 'amie / petite amie', 'nl-fr', 'Mijn vriendin woont in Gent.'),
('buur', 'voisin / voisine', 'nl-fr', 'Mijn buur heeft een grote tuin.'),
('collega', 'collègue', 'nl-fr', 'Mijn collega werkt hard.'),
('familie', 'famille', 'nl-fr', 'Mijn familie is heel groot.'),
('ouders', 'parents', 'nl-fr', 'Mijn ouders wonen in Den Haag.'),
('echtgenoot', 'époux / mari', 'nl-fr', 'Haar echtgenoot is piloot.'),
('tweeling', 'jumeaux', 'nl-fr', 'Ze heeft een tweelingbroer.'),
('volwassene', 'adulte', 'nl-fr', 'Volwassenen betalen meer.'),
('bejaarde', 'personne âgée', 'nl-fr', 'We helpen bejaarden in het dorp.'),
('tiener', 'adolescent', 'nl-fr', 'Tieners houden van muziek.'),
('persoon', 'personne', 'nl-fr', 'Er is een persoon aan de deur.'),

-- NOURRITURE & BOISSONS (68)
('brood', 'pain', 'nl-fr', 'Ik eet elke ochtend brood.'),
('boter', 'beurre', 'nl-fr', 'Ik smeer boter op mijn brood.'),
('kaas', 'fromage', 'nl-fr', 'Nederland is bekend om zijn kaas.'),
('melk', 'lait', 'nl-fr', 'Ik drink elke ochtend een glas melk.'),
('ei', 'œuf', 'nl-fr', 'Ik eet een gebakken ei.'),
('vlees', 'viande', 'nl-fr', 'We eten vlees bij het avondeten.'),
('kip', 'poulet', 'nl-fr', 'Gegrilde kip is lekker.'),
('vis', 'poisson', 'nl-fr', 'We eten vis op vrijdag.'),
('garnaal', 'crevette', 'nl-fr', 'Garnalen zijn mijn favoriet.'),
('rijst', 'riz', 'nl-fr', 'We eten rijst met groente.'),
('pasta', 'pâtes', 'nl-fr', 'Pasta met tomatensaus is lekker.'),
('aardappel', 'pomme de terre', 'nl-fr', 'We eten aardappelen bij het avondeten.'),
('wortel', 'carotte', 'nl-fr', 'Wortels zijn goed voor je ogen.'),
('tomaat', 'tomate', 'nl-fr', 'De tomaat is rood en sappig.'),
('ui', 'oignon', 'nl-fr', 'Ik snijd een ui voor de soep.'),
('knoflook', 'ail', 'nl-fr', 'Knoflook geeft veel smaak.'),
('sla', 'laitue / salade', 'nl-fr', 'Ik eet een salade met sla.'),
('appel', 'pomme', 'nl-fr', 'Een appel per dag houdt de dokter weg.'),
('peer', 'poire', 'nl-fr', 'De peer is zoet en sappig.'),
('banaan', 'banane', 'nl-fr', 'De banaan is geel en zoet.'),
('aardbei', 'fraise', 'nl-fr', 'Aardbeien zijn mijn favoriete fruit.'),
('druif', 'raisin', 'nl-fr', 'Druiven zijn lekker in de zomer.'),
('sinaasappel', 'orange', 'nl-fr', 'Ik pers een sinaasappel voor het sap.'),
('citroen', 'citron', 'nl-fr', 'Ik doe citroen in mijn thee.'),
('suiker', 'sucre', 'nl-fr', 'Ik doe geen suiker in mijn koffie.'),
('zout', 'sel', 'nl-fr', 'Doe wat zout in het water.'),
('peper', 'poivre', 'nl-fr', 'Peper maakt het eten lekkerder.'),
('olie', 'huile', 'nl-fr', 'Ik bak de uien in olie.'),
('soep', 'soupe', 'nl-fr', 'Tomatensoep is lekker in de winter.'),
('pizza', 'pizza', 'nl-fr', 'We bestellen pizza voor het avondeten.'),
('hamburger', 'hamburger', 'nl-fr', 'Een hamburger met friet is lekker.'),
('taart', 'tarte / gâteau', 'nl-fr', 'We eten taart op mijn verjaardag.'),
('koekje', 'biscuit', 'nl-fr', 'Ik eet een koekje bij mijn thee.'),
('chocolade', 'chocolat', 'nl-fr', 'Ik hou van donkere chocolade.'),
('ijs', 'glace', 'nl-fr', 'In de zomer eet ik graag ijs.'),
('water', 'eau', 'nl-fr', 'Ik drink veel water per dag.'),
('koffie', 'café', 'nl-fr', 'Ik drink elke ochtend koffie.'),
('thee', 'thé', 'nl-fr', 'Wil je een kopje thee?'),
('bier', 'bière', 'nl-fr', 'Hij drinkt een biertje na het werk.'),
('wijn', 'vin', 'nl-fr', 'We drinken wijn bij het eten.'),
('jus', 'jus', 'nl-fr', 'Ik drink sinaasappeljus.'),
('limonade', 'limonade', 'nl-fr', 'Kinderen drinken graag limonade.'),
('fles', 'bouteille', 'nl-fr', 'Ik koop een fles water.'),
('glas', 'verre', 'nl-fr', 'Geef me een glas water.'),
('bord', 'assiette', 'nl-fr', 'Leg het eten op het bord.'),
('vork', 'fourchette', 'nl-fr', 'Ik eet met een vork.'),
('mes', 'couteau', 'nl-fr', 'Ik snijd het brood met een mes.'),
('lepel', 'cuillère', 'nl-fr', 'Ik eet de soep met een lepel.'),
('pan', 'casserole / poêle', 'nl-fr', 'Ik kook de soep in een pan.'),
('ontbijt', 'petit-déjeuner', 'nl-fr', 'Ik eet elke ochtend ontbijt.'),
('lunch', 'déjeuner', 'nl-fr', 'We eten brood voor de lunch.'),
('diner', 'dîner', 'nl-fr', 'We eten warm eten voor het diner.'),
('groente', 'légumes', 'nl-fr', 'Eet elke dag veel groente.'),
('fruit', 'fruit', 'nl-fr', 'Fruit is gezond.'),
('restaurant', 'restaurant', 'nl-fr', 'We gaan vanavond naar een restaurant.'),
('menu', 'menu', 'nl-fr', 'Mag ik het menu zien?'),
('maaltijd', 'repas', 'nl-fr', 'We hebben drie maaltijden per dag.'),
('honger', 'faim', 'nl-fr', 'Ik heb honger, wanneer eten we?'),
('dorst', 'soif', 'nl-fr', 'Ik heb dorst, geef me water.'),
('zoet', 'sucré / doux', 'nl-fr', 'Deze appel is heel zoet.'),
('zuur', 'acide / aigre', 'nl-fr', 'De citroen is zuur.'),
('bitter', 'amer', 'nl-fr', 'Koffie is bitter.'),
('pittig', 'épicé / piquant', 'nl-fr', 'Dit eten is te pittig voor mij.'),
('vers', 'frais', 'nl-fr', 'Ik koop verse groenten op de markt.'),
('friet', 'frites', 'nl-fr', 'Friet met mayonaise is typisch Belgisch.'),
('salade', 'salade', 'nl-fr', 'Ik eet een groene salade.'),
('snoep', 'bonbons / friandises', 'nl-fr', 'Kinderen eten graag snoep.'),
('recept', 'recette', 'nl-fr', 'Dit is een oud recept van mijn grootmoeder.'),

-- ANIMAUX (50)
('hond', 'chien', 'nl-fr', 'Mijn hond heet Max.'),
('kat', 'chat', 'nl-fr', 'De kat slaapt op de bank.'),
('paard', 'cheval', 'nl-fr', 'Het paard rent door het veld.'),
('koe', 'vache', 'nl-fr', 'De koe geeft melk.'),
('schaap', 'mouton', 'nl-fr', 'Het schaap heeft witte wol.'),
('geit', 'chèvre', 'nl-fr', 'De geit eet gras.'),
('varken', 'cochon', 'nl-fr', 'Het varken leeft op de boerderij.'),
('eend', 'canard', 'nl-fr', 'De eend zwemt in de vijver.'),
('konijn', 'lapin', 'nl-fr', 'Het konijn eet wortels.'),
('muis', 'souris', 'nl-fr', 'De kat jaagt op de muis.'),
('vogel', 'oiseau', 'nl-fr', 'De vogel zingt in de boom.'),
('slang', 'serpent', 'nl-fr', 'De slang sist.'),
('kikker', 'grenouille', 'nl-fr', 'De kikker springt in de vijver.'),
('beer', 'ours', 'nl-fr', 'De beer slaapt in de winter.'),
('leeuw', 'lion', 'nl-fr', 'De leeuw is de koning van de jungle.'),
('tijger', 'tigre', 'nl-fr', 'De tijger heeft strepen.'),
('olifant', 'éléphant', 'nl-fr', 'De olifant heeft een lange slurf.'),
('giraffe', 'girafe', 'nl-fr', 'De giraffe heeft een lange nek.'),
('zebra', 'zèbre', 'nl-fr', 'De zebra heeft zwart-witte strepen.'),
('aap', 'singe', 'nl-fr', 'De aap klimt in de boom.'),
('wolf', 'loup', 'nl-fr', 'De wolf huilt naar de maan.'),
('vos', 'renard', 'nl-fr', 'De vos is slim.'),
('hert', 'cerf', 'nl-fr', 'Het hert loopt door het bos.'),
('eekhoorn', 'écureuil', 'nl-fr', 'De eekhoorn verzamelt noten.'),
('vlinder', 'papillon', 'nl-fr', 'De vlinder vliegt van bloem tot bloem.'),
('bij', 'abeille', 'nl-fr', 'De bij maakt honing.'),
('spin', 'araignée', 'nl-fr', 'De spin maakt een web.'),
('mug', 'moustique', 'nl-fr', 'De mug bijt me in mijn arm.'),
('adelaar', 'aigle', 'nl-fr', 'De adelaar vliegt hoog in de lucht.'),
('uil', 'hibou', 'nl-fr', 'De uil is actief s nachts.'),
('dolfijn', 'dauphin', 'nl-fr', 'De dolfijn is een slim dier.'),
('walvis', 'baleine', 'nl-fr', 'De blauwe walvis is het grootste dier.'),
('haai', 'requin', 'nl-fr', 'De haai zwemt in de oceaan.'),
('krab', 'crabe', 'nl-fr', 'De krab loopt zijwaarts.'),
('schildpad', 'tortue', 'nl-fr', 'De schildpad loopt langzaam.'),
('krokodil', 'crocodile', 'nl-fr', 'De krokodil ligt in de zon.'),
('papegaai', 'perroquet', 'nl-fr', 'De papegaai kan praten.'),
('neushoorn', 'rhinocéros', 'nl-fr', 'De neushoorn heeft een hoorn.'),
('nijlpaard', 'hippopotame', 'nl-fr', 'Het nijlpaard leeft in het water.'),
('kameel', 'chameau', 'nl-fr', 'De kameel leeft in de woestijn.'),
('kangoeroe', 'kangourou', 'nl-fr', 'De kangoeroe springt ver.'),
('pinguïn', 'pingouin', 'nl-fr', 'De pinguïn leeft in de kou.'),
('vlieg', 'mouche', 'nl-fr', 'De vlieg zit op het eten.'),
('mier', 'fourmi', 'nl-fr', 'De mier is heel sterk.'),
('libelle', 'libellule', 'nl-fr', 'De libelle vliegt boven het water.'),
('kreeft', 'homard', 'nl-fr', 'Kreeft is een duur gerecht.'),
('octopus', 'pieuvre', 'nl-fr', 'De octopus heeft acht tentakels.'),
('lama', 'lama', 'nl-fr', 'De lama komt uit Zuid-Amerika.'),
('rat', 'rat', 'nl-fr', 'De rat sluipt door de kelder.'),
('haas', 'lièvre', 'nl-fr', 'De haas rent snel door het veld.'),

-- NATURE & ENVIRONNEMENT (28)
('boom', 'arbre', 'nl-fr', 'De boom in de tuin is erg oud.'),
('bloem', 'fleur', 'nl-fr', 'De bloemen zijn mooi in de lente.'),
('gras', 'herbe / gazon', 'nl-fr', 'Het gras is groen en fris.'),
('plant', 'plante', 'nl-fr', 'Ik water de planten elke dag.'),
('blad', 'feuille', 'nl-fr', 'De bladeren vallen in de herfst.'),
('tak', 'branche', 'nl-fr', 'De vogel zit op een tak.'),
('bos', 'forêt', 'nl-fr', 'We wandelen door het bos.'),
('park', 'parc', 'nl-fr', 'We spelen in het park.'),
('berg', 'montagne', 'nl-fr', 'We beklimmen de berg.'),
('rivier', 'rivière / fleuve', 'nl-fr', 'De rivier stroomt naar de zee.'),
('meer', 'lac', 'nl-fr', 'We zwemmen in het meer.'),
('zee', 'mer', 'nl-fr', 'We gaan naar de zee in de zomer.'),
('oceaan', 'océan', 'nl-fr', 'De Atlantische Oceaan is enorm.'),
('strand', 'plage', 'nl-fr', 'We liggen op het strand.'),
('eiland', 'île', 'nl-fr', 'Het eiland is omgeven door water.'),
('woestijn', 'désert', 'nl-fr', 'De woestijn is erg warm.'),
('steen', 'pierre / roche', 'nl-fr', 'Ik gooi een steen in de vijver.'),
('zand', 'sable', 'nl-fr', 'Het strand heeft fijn wit zand.'),
('aarde', 'terre / sol', 'nl-fr', 'De aarde is onze planeet.'),
('ster', 'étoile', 'nl-fr', 'Ik zie veel sterren vannacht.'),
('maan', 'lune', 'nl-fr', 'De maan schijnt helder.'),
('planeet', 'planète', 'nl-fr', 'Aarde is een planeet.'),
('natuur', 'nature', 'nl-fr', 'Ik hou van de natuur.'),
('milieu', 'environnement', 'nl-fr', 'We moeten het milieu beschermen.'),
('waterval', 'cascade', 'nl-fr', 'De waterval is indrukwekkend.'),
('vulkaan', 'volcan', 'nl-fr', 'De vulkaan barstte uit.'),
('veld', 'champ', 'nl-fr', 'De koeien lopen in het veld.'),
('horizon', 'horizon', 'nl-fr', 'De zon zakt achter de horizon.'),

-- MAISON & MEUBLES (48)
('huis', 'maison', 'nl-fr', 'Ik woon in een klein huis.'),
('appartement', 'appartement', 'nl-fr', 'Ze woont in een appartement in de stad.'),
('kamer', 'chambre / pièce', 'nl-fr', 'Mijn kamer is op de eerste verdieping.'),
('woonkamer', 'salon / salle de séjour', 'nl-fr', 'We kijken tv in de woonkamer.'),
('slaapkamer', 'chambre à coucher', 'nl-fr', 'Mijn slaapkamer is groot.'),
('badkamer', 'salle de bain', 'nl-fr', 'De badkamer heeft een douche.'),
('keuken', 'cuisine', 'nl-fr', 'Ik kook in de keuken.'),
('eetkamer', 'salle à manger', 'nl-fr', 'We eten in de eetkamer.'),
('gang', 'couloir / entrée', 'nl-fr', 'De gang is smal.'),
('trap', 'escalier', 'nl-fr', 'Ik loop de trap op.'),
('deur', 'porte', 'nl-fr', 'Open de deur, alsjeblieft.'),
('raam', 'fenêtre', 'nl-fr', 'Ik open het raam.'),
('vloer', 'sol / plancher', 'nl-fr', 'De vloer is van hout.'),
('plafond', 'plafond', 'nl-fr', 'Het plafond is wit.'),
('muur', 'mur', 'nl-fr', 'De muur is blauw geschilderd.'),
('dak', 'toit', 'nl-fr', 'Het dak is rood.'),
('garage', 'garage', 'nl-fr', 'De auto staat in de garage.'),
('kelder', 'cave / sous-sol', 'nl-fr', 'Wijn wordt in de kelder bewaard.'),
('zolder', 'grenier', 'nl-fr', 'Oude spullen staan op de zolder.'),
('tafel', 'table', 'nl-fr', 'We eten aan tafel.'),
('stoel', 'chaise', 'nl-fr', 'Ga zitten op de stoel.'),
('bank', 'canapé', 'nl-fr', 'Ik zit op de bank en kijk tv.'),
('bed', 'lit', 'nl-fr', 'Ik ga naar bed om tien uur.'),
('kast', 'armoire / placard', 'nl-fr', 'Mijn kleren zitten in de kast.'),
('bureau', 'bureau', 'nl-fr', 'Ik werk aan mijn bureau.'),
('lamp', 'lampe', 'nl-fr', 'Zet de lamp aan, het is donker.'),
('spiegel', 'miroir', 'nl-fr', 'Ik kijk in de spiegel.'),
('tapijt', 'tapis', 'nl-fr', 'Het tapijt is rood.'),
('gordijn', 'rideau', 'nl-fr', 'De gordijnen zijn dicht.'),
('koelkast', 'réfrigérateur / frigo', 'nl-fr', 'Het eten staat in de koelkast.'),
('oven', 'four', 'nl-fr', 'Ik zet de oven op 180 graden.'),
('wasmachine', 'machine à laver', 'nl-fr', 'Ik was mijn kleren in de wasmachine.'),
('douche', 'douche', 'nl-fr', 'Ik neem een douche elke ochtend.'),
('bad', 'bain / baignoire', 'nl-fr', 'Ik neem een lekker bad.'),
('toilet', 'toilettes', 'nl-fr', 'Waar is het toilet?'),
('zeep', 'savon', 'nl-fr', 'Was je handen met zeep.'),
('handdoek', 'serviette', 'nl-fr', 'Droog je handen met de handdoek.'),
('sleutel', 'clé', 'nl-fr', 'Ik vergeet altijd mijn sleutel.'),
('bel', 'sonnette', 'nl-fr', 'Ring de bel als je aankomt.'),
('tv', 'télévision', 'nl-fr', 'We kijken naar de tv.'),
('verdieping', 'étage', 'nl-fr', 'Ik woon op de derde verdieping.'),
('lift', 'ascenseur', 'nl-fr', 'Neem de lift naar de vijfde etage.'),
('balkon', 'balcon', 'nl-fr', 'Ik drink koffie op het balkon.'),
('terras', 'terrasse', 'nl-fr', 'We eten buiten op het terras.'),
('brievenbus', 'boîte aux lettres', 'nl-fr', 'De post zit in de brievenbus.'),
('adres', 'adresse', 'nl-fr', 'Wat is jouw adres?'),
('woning', 'logement / habitation', 'nl-fr', 'Ze zoekt een nieuwe woning.'),
('kussen', 'coussin / oreiller', 'nl-fr', 'Ik slaap met twee kussens.'),

-- VÊTEMENTS & ACCESSOIRES (35)
('kleren', 'vêtements', 'nl-fr', 'Ik koop nieuwe kleren in de winkel.'),
('trui', 'pull / sweat', 'nl-fr', 'Ik draag een warme trui.'),
('shirt', 'chemise / t-shirt', 'nl-fr', 'Hij draagt een wit shirt.'),
('broek', 'pantalon', 'nl-fr', 'Mijn broek is blauw.'),
('rok', 'jupe', 'nl-fr', 'Ze draagt een rode rok.'),
('jurk', 'robe', 'nl-fr', 'Ze heeft een mooie jurk aan.'),
('jas', 'manteau / veste', 'nl-fr', 'Trek een jas aan, het is koud.'),
('regenjas', 'imperméable', 'nl-fr', 'Ik draag een regenjas als het regent.'),
('sjaal', 'écharpe', 'nl-fr', 'Ik draag een sjaal in de winter.'),
('hoed', 'chapeau', 'nl-fr', 'Hij draagt een hoed in de zon.'),
('pet', 'casquette', 'nl-fr', 'Hij draagt altijd een pet.'),
('handschoenen', 'gants', 'nl-fr', 'Ik draag handschoenen in de winter.'),
('sokken', 'chaussettes', 'nl-fr', 'Ik doe warme sokken aan.'),
('schoenen', 'chaussures', 'nl-fr', 'Mijn schoenen zijn nieuw.'),
('laarzen', 'bottes', 'nl-fr', 'Ik draag laarzen in de regen.'),
('sandalen', 'sandales', 'nl-fr', 'In de zomer draag ik sandalen.'),
('pyama', 'pyjama', 'nl-fr', 'Ik doe mijn pyama aan voor het slapen.'),
('riem', 'ceinture', 'nl-fr', 'Ik draag een zwarte riem.'),
('das', 'cravate', 'nl-fr', 'Hij draagt een das naar zijn werk.'),
('horloge', 'montre', 'nl-fr', 'Ik kijk op mijn horloge.'),
('bril', 'lunettes', 'nl-fr', 'Ik draag een bril om beter te zien.'),
('tas', 'sac', 'nl-fr', 'Ik draag een grote tas.'),
('rugzak', 'sac à dos', 'nl-fr', 'Mijn rugzak is zwaar van de boeken.'),
('portemonnee', 'portefeuille', 'nl-fr', 'Ik laat mijn portemonnee thuis.'),
('ring', 'bague / anneau', 'nl-fr', 'Ze draagt een gouden ring.'),
('ketting', 'collier / chaîne', 'nl-fr', 'Ze heeft een mooie ketting om.'),
('oorbel', 'boucle d oreille', 'nl-fr', 'Ze draagt zilveren oorbellen.'),
('maat', 'taille / pointure', 'nl-fr', 'Welke maat heeft u?'),
('uniform', 'uniforme', 'nl-fr', 'De leerlingen dragen een uniform.'),
('zwempak', 'maillot de bain', 'nl-fr', 'Ik doe mijn zwempak aan voor het zwemmen.'),
('vest', 'veste / gilet', 'nl-fr', 'Hij draagt een grijs vest.'),
('hemd', 'chemise', 'nl-fr', 'Hij draagt een wit hemd.'),
('muts', 'bonnet', 'nl-fr', 'Ik draag een muts in de winter.'),
('rits', 'fermeture éclair', 'nl-fr', 'De rits van mijn jas is kapot.'),
('knoop', 'bouton', 'nl-fr', 'Er mist een knoop aan mijn jas.'),

-- TRANSPORT (28)
('auto', 'voiture', 'nl-fr', 'Ik rijd naar mijn werk met de auto.'),
('fiets', 'vélo', 'nl-fr', 'Ik ga naar school op de fiets.'),
('motor', 'moto', 'nl-fr', 'Hij rijdt op een motor.'),
('bus', 'bus', 'nl-fr', 'Ik neem de bus naar het centrum.'),
('trein', 'train', 'nl-fr', 'De trein van Amsterdam naar Rotterdam duurt een uur.'),
('metro', 'métro', 'nl-fr', 'We nemen de metro naar het station.'),
('tram', 'tram', 'nl-fr', 'De tram rijdt door het centrum.'),
('vliegtuig', 'avion', 'nl-fr', 'We vliegen naar Parijs.'),
('boot', 'bateau', 'nl-fr', 'We varen met de boot.'),
('taxi', 'taxi', 'nl-fr', 'Ik neem een taxi naar het hotel.'),
('vrachtwagen', 'camion', 'nl-fr', 'De vrachtwagen rijdt op de snelweg.'),
('rijbewijs', 'permis de conduire', 'nl-fr', 'Ik heb mijn rijbewijs gehaald.'),
('benzine', 'essence', 'nl-fr', 'Ik moet benzine tanken.'),
('station', 'gare', 'nl-fr', 'De trein vertrekt van het station.'),
('luchthaven', 'aéroport', 'nl-fr', 'We rijden naar de luchthaven.'),
('haven', 'port', 'nl-fr', 'De boot vertrekt vanuit de haven.'),
('weg', 'route / chemin', 'nl-fr', 'De weg naar het centrum is lang.'),
('straat', 'rue', 'nl-fr', 'Ik woon in een rustige straat.'),
('brug', 'pont', 'nl-fr', 'We rijden over de brug.'),
('tunnel', 'tunnel', 'nl-fr', 'De tunnel gaat onder de rivier door.'),
('rotonde', 'rond-point', 'nl-fr', 'Ga rechtdoor bij de rotonde.'),
('snelweg', 'autoroute', 'nl-fr', 'We rijden op de snelweg.'),
('verkeer', 'circulation / trafic', 'nl-fr', 'Er is veel verkeer op de weg.'),
('halte', 'arrêt', 'nl-fr', 'Ik wacht bij de bushalte.'),
('kaartje', 'ticket / billet', 'nl-fr', 'Ik koop een kaartje voor de trein.'),
('perron', 'quai', 'nl-fr', 'De trein staat op perron drie.'),
('bagage', 'bagages', 'nl-fr', 'Mijn bagage is te zwaar.'),
('parkeerplaats', 'parking / place de stationnement', 'nl-fr', 'Ik zoek een parkeerplaats.'),

-- ÉCOLE & TRAVAIL (42)
('school', 'école', 'nl-fr', 'Ik ga elke dag naar school.'),
('klas', 'classe', 'nl-fr', 'Er zijn twintig leerlingen in mijn klas.'),
('leerling', 'élève', 'nl-fr', 'De leerlingen werken hard.'),
('leraar', 'professeur / instituteur', 'nl-fr', 'Mijn leraar is heel goed.'),
('boek', 'livre', 'nl-fr', 'Ik lees een interessant boek.'),
('schrift', 'cahier', 'nl-fr', 'Ik schrijf in mijn schrift.'),
('pen', 'stylo', 'nl-fr', 'Kan ik een pen lenen?'),
('potlood', 'crayon', 'nl-fr', 'Ik teken met een potlood.'),
('gum', 'gomme', 'nl-fr', 'Ik gebruik de gum om fouten te wissen.'),
('les', 'cours / leçon', 'nl-fr', 'De les begint om negen uur.'),
('huiswerk', 'devoirs', 'nl-fr', 'Ik doe mijn huiswerk na school.'),
('examen', 'examen', 'nl-fr', 'Morgen heb ik een examen.'),
('cijfer', 'note', 'nl-fr', 'Ik heb een goed cijfer gehaald.'),
('diploma', 'diplôme', 'nl-fr', 'Ze heeft haar diploma gehaald.'),
('universiteit', 'université', 'nl-fr', 'Hij studeert aan de universiteit.'),
('wiskunde', 'mathématiques', 'nl-fr', 'Wiskunde is mijn favoriete vak.'),
('taal', 'langue', 'nl-fr', 'Ik leer een nieuwe taal.'),
('kantoor', 'bureau', 'nl-fr', 'Ik werk in een kantoor.'),
('werk', 'travail', 'nl-fr', 'Ik ga naar mijn werk.'),
('baan', 'emploi / poste', 'nl-fr', 'Ik heb een nieuwe baan gevonden.'),
('salaris', 'salaire', 'nl-fr', 'Mijn salaris is goed.'),
('vergadering', 'réunion', 'nl-fr', 'Ik heb een vergadering om drie uur.'),
('e-mail', 'e-mail / courriel', 'nl-fr', 'Ik stuur je een e-mail.'),
('brief', 'lettre', 'nl-fr', 'Ik schrijf een brief aan mijn vriend.'),
('vakantie', 'vacances', 'nl-fr', 'In de zomer heb ik vakantie.'),
('baas', 'patron / chef', 'nl-fr', 'Mijn baas is streng.'),
('solliciteren', 'postuler', 'nl-fr', 'Ik solliciteer voor een nieuwe baan.'),
('stage', 'stage', 'nl-fr', 'Ik doe een stage bij een bedrijf.'),
('bedrijf', 'entreprise', 'nl-fr', 'Ze werkt voor een groot bedrijf.'),
('rapport', 'rapport', 'nl-fr', 'Ik schrijf een rapport.'),
('project', 'projet', 'nl-fr', 'We werken aan een nieuw project.'),
('deadline', 'date limite', 'nl-fr', 'De deadline is vrijdag.'),
('geschiedenis', 'histoire', 'nl-fr', 'Ik hou van geschiedenis.'),
('aardrijkskunde', 'géographie', 'nl-fr', 'We leren over landen in aardrijkskunde.'),
('kunst', 'art', 'nl-fr', 'Ik hou van moderne kunst.'),
('muziek', 'musique', 'nl-fr', 'Muziek maakt me gelukkig.'),
('bibliotheek', 'bibliothèque', 'nl-fr', 'Ik leen boeken uit de bibliotheek.'),
('computer', 'ordinateur', 'nl-fr', 'Ik werk op de computer.'),
('vergadering', 'réunion / assemblée', 'nl-fr', 'De vergadering duurt twee uur.'),
('ontslag', 'licenciement / démission', 'nl-fr', 'Hij kreeg ontslag.'),
('toets', 'test / interrogation', 'nl-fr', 'Morgen heb ik een toets.'),
('boekentas', 'cartable', 'nl-fr', 'Mijn boekentas is zwaar.'),

-- SANTÉ (26)
('gezondheid', 'santé', 'nl-fr', 'Gezondheid is het belangrijkste.'),
('ziek', 'malade', 'nl-fr', 'Ik ben ziek vandaag.'),
('pijn', 'douleur / mal', 'nl-fr', 'Ik heb pijn in mijn rug.'),
('koorts', 'fièvre', 'nl-fr', 'Ik heb koorts.'),
('hoesten', 'tousser', 'nl-fr', 'Hij hoest al drie dagen.'),
('griep', 'grippe', 'nl-fr', 'Ik heb de griep.'),
('hoofdpijn', 'mal de tête', 'nl-fr', 'Ik heb hoofdpijn.'),
('buikpijn', 'mal de ventre', 'nl-fr', 'Het kind heeft buikpijn.'),
('allergie', 'allergie', 'nl-fr', 'Ik heb een allergie voor noten.'),
('wond', 'blessure / plaie', 'nl-fr', 'Ik heb een wond aan mijn hand.'),
('ziekenhuis', 'hôpital', 'nl-fr', 'Ik ga naar het ziekenhuis.'),
('dokter', 'médecin / docteur', 'nl-fr', 'Ik ga naar de dokter.'),
('verpleegkundige', 'infirmier / infirmière', 'nl-fr', 'De verpleegkundige helpt de patiënt.'),
('medicijn', 'médicament', 'nl-fr', 'Ik neem medicijnen voor mijn allergie.'),
('pil', 'pilule / comprimé', 'nl-fr', 'Ik neem een pil voor de pijn.'),
('apotheek', 'pharmacie', 'nl-fr', 'Ik haal mijn medicijnen bij de apotheek.'),
('herstel', 'rétablissement / guérison', 'nl-fr', 'Goed herstel!'),
('rust', 'repos', 'nl-fr', 'Je moet rust nemen.'),
('operatie', 'opération', 'nl-fr', 'Ze heeft een operatie gehad.'),
('tandarts', 'dentiste', 'nl-fr', 'Ik ga naar de tandarts.'),
('ambulance', 'ambulance', 'nl-fr', 'Bel de ambulance, het is urgent!'),
('bloeddruk', 'tension artérielle', 'nl-fr', 'Mijn bloeddruk is normaal.'),
('dieet', 'régime alimentaire', 'nl-fr', 'Ik volg een gezond dieet.'),
('vitamine', 'vitamine', 'nl-fr', 'Ik neem elke ochtend een vitamine.'),
('gewicht', 'poids', 'nl-fr', 'Mijn gewicht is stabiel.'),
('ziekte', 'maladie', 'nl-fr', 'Het is een ernstige ziekte.'),

-- SPORTS & LOISIRS (32)
('voetbal', 'football', 'nl-fr', 'Ik speel voetbal op woensdag.'),
('basketbal', 'basket-ball', 'nl-fr', 'Hij speelt basketbal in een club.'),
('tennis', 'tennis', 'nl-fr', 'Ze speelt tennis elke week.'),
('zwemmen', 'nager / natation', 'nl-fr', 'Ik zwem graag in de zomer.'),
('fietsen', 'faire du vélo / cyclisme', 'nl-fr', 'Fietsen is gezond.'),
('hardlopen', 'courir / jogging', 'nl-fr', 'Ik loop elke ochtend hard.'),
('wandelen', 'marcher / se promener', 'nl-fr', 'We gaan wandelen in het bos.'),
('yoga', 'yoga', 'nl-fr', 'Ik doe yoga voor ontspanning.'),
('dansen', 'danser', 'nl-fr', 'Ze danst salsa.'),
('zingen', 'chanter', 'nl-fr', 'Hij zingt in een koor.'),
('gitaar', 'guitare', 'nl-fr', 'Ik speel gitaar.'),
('piano', 'piano', 'nl-fr', 'Ze speelt piano.'),
('fotograferen', 'photographier', 'nl-fr', 'Ze fotografeert de natuur.'),
('reizen', 'voyager', 'nl-fr', 'Ik reiz elk jaar naar een nieuw land.'),
('kamperen', 'camper', 'nl-fr', 'We kamperen in de Ardennen.'),
('vissen', 'pêcher', 'nl-fr', 'Mijn vader gaat graag vissen.'),
('skiën', 'skier', 'nl-fr', 'In de winter gaan we skiën.'),
('schaatsen', 'patiner', 'nl-fr', 'We gaan schaatsen op het ijs.'),
('hockey', 'hockey', 'nl-fr', 'Ze speelt hockey.'),
('golf', 'golf', 'nl-fr', 'Mijn oom speelt golf.'),
('film', 'film', 'nl-fr', 'We kijken een film vanavond.'),
('theater', 'théâtre', 'nl-fr', 'We gaan naar het theater.'),
('museum', 'musée', 'nl-fr', 'Ik bezoek graag musea.'),
('wedstrijd', 'match / compétition', 'nl-fr', 'We kijken naar de wedstrijd.'),
('kampioenschap', 'championnat', 'nl-fr', 'Het kampioenschap begint volgende week.'),
('club', 'club', 'nl-fr', 'Ik ben lid van een sportclub.'),
('stadion', 'stade', 'nl-fr', 'We gaan naar het stadion.'),
('trainer', 'entraîneur', 'nl-fr', 'Onze trainer is heel goed.'),
('speler', 'joueur', 'nl-fr', 'Hij is een goede speler.'),
('team', 'équipe', 'nl-fr', 'Ons team wint vanavond.'),
('hobby', 'loisir / passe-temps', 'nl-fr', 'Wat is jouw hobby?'),
('tekenen', 'dessiner', 'nl-fr', 'Ik teken graag portretten.'),

-- TECHNOLOGIE (22)
('laptop', 'ordinateur portable', 'nl-fr', 'Ik neem mijn laptop mee.'),
('tablet', 'tablette', 'nl-fr', 'Mijn kind gebruikt een tablet.'),
('telefoon', 'téléphone', 'nl-fr', 'Mijn telefoon is leeg.'),
('smartphone', 'smartphone', 'nl-fr', 'Ik koop een nieuwe smartphone.'),
('internet', 'internet', 'nl-fr', 'Ik gebruik internet voor mijn werk.'),
('website', 'site web', 'nl-fr', 'Ik maak een website.'),
('app', 'application', 'nl-fr', 'Ik download een nieuwe app.'),
('programma', 'programme / logiciel', 'nl-fr', 'Dit programma werkt niet.'),
('toetsenbord', 'clavier', 'nl-fr', 'Mijn toetsenbord is kapot.'),
('scherm', 'écran', 'nl-fr', 'Het scherm is groot.'),
('printer', 'imprimante', 'nl-fr', 'Ik print het document.'),
('camera', 'caméra / appareil photo', 'nl-fr', 'Ik maak foto s met mijn camera.'),
('televisie', 'télévision', 'nl-fr', 'We kijken televisie na het eten.'),
('radio', 'radio', 'nl-fr', 'Ik luister naar de radio.'),
('batterij', 'batterie / pile', 'nl-fr', 'Mijn batterij is bijna leeg.'),
('oplader', 'chargeur', 'nl-fr', 'Ik vergeet altijd mijn oplader.'),
('wifi', 'wifi', 'nl-fr', 'Wat is het wifi-wachtwoord?'),
('wachtwoord', 'mot de passe', 'nl-fr', 'Ik vergeet mijn wachtwoord.'),
('downloaden', 'télécharger', 'nl-fr', 'Ik download een film.'),
('uploaden', 'uploader / téléverser', 'nl-fr', 'Ik upload een foto.'),
('opslaan', 'enregistrer / sauvegarder', 'nl-fr', 'Vergeet niet je werk op te slaan.'),
('social media', 'réseaux sociaux', 'nl-fr', 'Ik gebruik social media elke dag.'),

-- SHOPPING & ARGENT (20)
('winkel', 'magasin', 'nl-fr', 'Ik ga naar de winkel.'),
('markt', 'marché', 'nl-fr', 'Ik koop groente op de markt.'),
('prijs', 'prix', 'nl-fr', 'Wat is de prijs?'),
('geld', 'argent', 'nl-fr', 'Ik heb geen geld meer.'),
('euro', 'euro', 'nl-fr', 'Dit kost tien euro.'),
('betalen', 'payer', 'nl-fr', 'Ik betaal met mijn kaart.'),
('kopen', 'acheter', 'nl-fr', 'Ik wil dit kopen.'),
('verkopen', 'vendre', 'nl-fr', 'Hij verkoopt zijn auto.'),
('korting', 'réduction / remise', 'nl-fr', 'Er is tien procent korting.'),
('rekening', 'addition / facture', 'nl-fr', 'Mag ik de rekening?'),
('creditcard', 'carte de crédit', 'nl-fr', 'Ik betaal met mijn creditcard.'),
('bon', 'ticket de caisse / bon', 'nl-fr', 'Ik bewaar de bon.'),
('kassa', 'caisse', 'nl-fr', 'Ik wacht bij de kassa.'),
('boodschappen', 'courses / emplettes', 'nl-fr', 'Ik doe boodschappen op zaterdag.'),
('supermarkt', 'supermarché', 'nl-fr', 'Ik ga naar de supermarkt.'),
('goedkoop', 'bon marché / pas cher', 'nl-fr', 'Dit is goedkoop.'),
('duur', 'cher', 'nl-fr', 'Dit restaurant is te duur.'),
('merk', 'marque', 'nl-fr', 'Welk merk is dit?'),
('wisselgeld', 'monnaie', 'nl-fr', 'Hier is uw wisselgeld.'),
('aanbieding', 'promotion / offre spéciale', 'nl-fr', 'Er is een aanbieding op appels.'),

-- VERBES COURANTS (100)
('zijn', 'être', 'nl-fr', 'Ik ben gelukkig.'),
('hebben', 'avoir', 'nl-fr', 'Ik heb een hond.'),
('doen', 'faire', 'nl-fr', 'Wat doe jij vandaag?'),
('gaan', 'aller', 'nl-fr', 'Ik ga naar het werk.'),
('komen', 'venir', 'nl-fr', 'Ze komt morgen.'),
('zien', 'voir', 'nl-fr', 'Ik zie de bergen.'),
('horen', 'entendre', 'nl-fr', 'Ik hoor muziek.'),
('spreken', 'parler', 'nl-fr', 'Ik spreek Nederlands.'),
('zeggen', 'dire', 'nl-fr', 'Wat zeg jij?'),
('vragen', 'demander', 'nl-fr', 'Ik vraag om hulp.'),
('antwoorden', 'répondre', 'nl-fr', 'Ik antwoord op de vraag.'),
('weten', 'savoir', 'nl-fr', 'Ik weet het antwoord.'),
('denken', 'penser', 'nl-fr', 'Ik denk dat het goed is.'),
('geloven', 'croire', 'nl-fr', 'Ik geloof je.'),
('willen', 'vouloir', 'nl-fr', 'Ik wil koffie.'),
('kunnen', 'pouvoir', 'nl-fr', 'Ik kan zwemmen.'),
('moeten', 'devoir', 'nl-fr', 'Ik moet werken.'),
('mogen', 'avoir le droit de', 'nl-fr', 'Mag ik binnenkomen?'),
('lopen', 'marcher', 'nl-fr', 'Ik loop naar school.'),
('rennen', 'courir', 'nl-fr', 'Hij rent elke ochtend.'),
('zitten', 'être assis', 'nl-fr', 'Ik zit op de bank.'),
('staan', 'être debout', 'nl-fr', 'Ik sta bij de bushalte.'),
('liggen', 'être couché', 'nl-fr', 'Ik lig in bed.'),
('slapen', 'dormir', 'nl-fr', 'Ik slaap acht uur.'),
('eten', 'manger', 'nl-fr', 'Ik eet een boterham.'),
('drinken', 'boire', 'nl-fr', 'Ik drink water.'),
('koken', 'cuisiner / cuire', 'nl-fr', 'Ik kook het avondeten.'),
('wassen', 'laver', 'nl-fr', 'Ik was mijn handen.'),
('schoonmaken', 'nettoyer', 'nl-fr', 'Ik maak het huis schoon.'),
('werken', 'travailler', 'nl-fr', 'Ik werk vijf dagen per week.'),
('studeren', 'étudier', 'nl-fr', 'Ze studeert medicijnen.'),
('spelen', 'jouer', 'nl-fr', 'De kinderen spelen buiten.'),
('lezen', 'lire', 'nl-fr', 'Ik lees elke avond.'),
('schrijven', 'écrire', 'nl-fr', 'Ik schrijf een brief.'),
('zingen', 'chanter', 'nl-fr', 'We zingen een lied.'),
('luisteren', 'écouter', 'nl-fr', 'Ik luister naar muziek.'),
('kijken', 'regarder', 'nl-fr', 'Ik kijk naar de film.'),
('wachten', 'attendre', 'nl-fr', 'Ik wacht op de bus.'),
('helpen', 'aider', 'nl-fr', 'Kan jij me helpen?'),
('geven', 'donner', 'nl-fr', 'Ik geef je het boek.'),
('nemen', 'prendre', 'nl-fr', 'Ik neem de bus.'),
('brengen', 'apporter / amener', 'nl-fr', 'Breng je iets mee?'),
('halen', 'aller chercher', 'nl-fr', 'Ik haal je op.'),
('zoeken', 'chercher', 'nl-fr', 'Ik zoek mijn sleutel.'),
('vinden', 'trouver', 'nl-fr', 'Ik vind het boek.'),
('verliezen', 'perdre', 'nl-fr', 'Ik verlies altijd mijn sleutel.'),
('winnen', 'gagner', 'nl-fr', 'We winnen de wedstrijd.'),
('beginnen', 'commencer', 'nl-fr', 'De les begint om negen uur.'),
('stoppen', 'arrêter / s arrêter', 'nl-fr', 'De bus stopt hier.'),
('openen', 'ouvrir', 'nl-fr', 'Open de deur.'),
('sluiten', 'fermer', 'nl-fr', 'Sluit het raam.'),
('rijden', 'conduire / rouler', 'nl-fr', 'Ik rijd naar huis.'),
('vliegen', 'voler / prendre l avion', 'nl-fr', 'We vliegen naar Japan.'),
('zwemmen', 'nager', 'nl-fr', 'Hij zwemt in het meer.'),
('proberen', 'essayer', 'nl-fr', 'Ik probeer het te begrijpen.'),
('vergeten', 'oublier', 'nl-fr', 'Ik vergeet altijd mijn sleutel.'),
('herinneren', 'se souvenir', 'nl-fr', 'Ik herinner me het niet.'),
('begrijpen', 'comprendre', 'nl-fr', 'Ik begrijp het niet.'),
('uitleggen', 'expliquer', 'nl-fr', 'Kun je het uitleggen?'),
('lachen', 'rire', 'nl-fr', 'We lachen om zijn grap.'),
('huilen', 'pleurer', 'nl-fr', 'Ze huilt van verdriet.'),
('glimlachen', 'sourire', 'nl-fr', 'Ze glimlacht altijd.'),
('bellen', 'appeler / téléphoner', 'nl-fr', 'Ik bel je morgen.'),
('sturen', 'envoyer', 'nl-fr', 'Ik stuur je een bericht.'),
('ontvangen', 'recevoir', 'nl-fr', 'Ik ontvang veel e-mails.'),
('organiseren', 'organiser', 'nl-fr', 'Ik organiseer het feest.'),
('plannen', 'planifier / prévoir', 'nl-fr', 'We plannen een vakantie.'),
('beslissen', 'décider', 'nl-fr', 'Ik moet een beslissing nemen.'),
('kiezen', 'choisir', 'nl-fr', 'Kies een kleur.'),
('veranderen', 'changer', 'nl-fr', 'Alles verandert.'),
('groeien', 'grandir / pousser', 'nl-fr', 'Kinderen groeien snel.'),
('bouwen', 'construire', 'nl-fr', 'Ze bouwen een nieuw huis.'),
('maken', 'faire / fabriquer', 'nl-fr', 'Ik maak een taart.'),
('breken', 'casser / briser', 'nl-fr', 'Het glas valt en breekt.'),
('repareren', 'réparer', 'nl-fr', 'Ik repareer de fiets.'),
('meten', 'mesurer', 'nl-fr', 'Ik meet de kamer op.'),
('tellen', 'compter', 'nl-fr', 'Ik tel het geld.'),
('reserveren', 'réserver', 'nl-fr', 'Ik reserveer een tafel.'),
('bestellen', 'commander', 'nl-fr', 'Ik bestel een pizza.'),
('controleren', 'vérifier / contrôler', 'nl-fr', 'Ik controleer mijn e-mails.'),
('ontmoeten', 'rencontrer', 'nl-fr', 'Ik ontmoet mijn vriend in het café.'),
('bezoeken', 'visiter / rendre visite', 'nl-fr', 'We bezoeken het museum.'),
('vertrekken', 'partir / quitter', 'nl-fr', 'De trein vertrekt over vijf minuten.'),
('aankomen', 'arriver', 'nl-fr', 'We komen morgen aan.'),
('terugkeren', 'revenir / retourner', 'nl-fr', 'Ik keer terug naar huis.'),
('dromen', 'rêver', 'nl-fr', 'Ik droom van een reis.'),
('hopen', 'espérer', 'nl-fr', 'Ik hoop dat het goed gaat.'),
('verwachten', 'attendre / s attendre à', 'nl-fr', 'Ik verwacht een pakket.'),
('feliciteren', 'féliciter', 'nl-fr', 'Ik feliciteer je met je verjaardag.'),
('bedanken', 'remercier', 'nl-fr', 'Ik bedank je voor je hulp.'),
('vertellen', 'raconter / dire', 'nl-fr', 'Vertel me wat er is gebeurd.'),
('vragen', 'interroger / poser une question', 'nl-fr', 'Mag ik je iets vragen?'),
('leren', 'apprendre', 'nl-fr', 'Ik leer Nederlands.'),
('onderwijzen', 'enseigner', 'nl-fr', 'Ze onderwijst wiskunde.'),
('kopen', 'acheter', 'nl-fr', 'Ik koop brood in de bakkerij.'),
('verkopen', 'vendre', 'nl-fr', 'Ze verkoopt bloemen.'),
('leven', 'vivre', 'nl-fr', 'We leven in een mooie wereld.'),
('sterven', 'mourir', 'nl-fr', 'Alle bloemen sterven in de winter.'),

-- ADJECTIFS (62)
('groot', 'grand / gros', 'nl-fr', 'Hij woont in een groot huis.'),
('klein', 'petit', 'nl-fr', 'Ze heeft een kleine hond.'),
('lang', 'long / grand', 'nl-fr', 'Hij heeft lang haar.'),
('kort', 'court / petit', 'nl-fr', 'Ze heeft kort haar.'),
('dik', 'épais / gros', 'nl-fr', 'Dit boek is dik.'),
('dun', 'mince / fin', 'nl-fr', 'Het papier is dun.'),
('hoog', 'haut', 'nl-fr', 'De berg is hoog.'),
('laag', 'bas', 'nl-fr', 'De prijs is laag.'),
('nieuw', 'nouveau / neuf', 'nl-fr', 'Ik heb een nieuwe auto.'),
('oud', 'vieux / ancien', 'nl-fr', 'Dit huis is heel oud.'),
('jong', 'jeune', 'nl-fr', 'Ze is jong en energiek.'),
('mooi', 'beau / belle', 'nl-fr', 'Het is een mooie dag.'),
('lelijk', 'laid', 'nl-fr', 'Het is een lelijk gebouw.'),
('schoon', 'propre', 'nl-fr', 'De keuken is schoon.'),
('vies', 'sale', 'nl-fr', 'Mijn handen zijn vies.'),
('goed', 'bon / bien', 'nl-fr', 'Dit is een goed boek.'),
('slecht', 'mauvais / mal', 'nl-fr', 'Dit weer is slecht.'),
('leuk', 'sympa / agréable', 'nl-fr', 'Wat een leuke dag!'),
('saai', 'ennuyeux', 'nl-fr', 'De film was saai.'),
('interessant', 'intéressant', 'nl-fr', 'Dit is een interessant verhaal.'),
('gemakkelijk', 'facile', 'nl-fr', 'Dit examen was gemakkelijk.'),
('moeilijk', 'difficile', 'nl-fr', 'Dit vak is moeilijk.'),
('snel', 'rapide / vite', 'nl-fr', 'De trein is snel.'),
('langzaam', 'lent', 'nl-fr', 'De schildpad is langzaam.'),
('sterk', 'fort', 'nl-fr', 'Hij is heel sterk.'),
('zwak', 'faible', 'nl-fr', 'Ze is nog zwak na haar ziekte.'),
('rijk', 'riche', 'nl-fr', 'Hij is een rijke man.'),
('arm', 'pauvre', 'nl-fr', 'Ze heeft niet veel geld.'),
('gelukkig', 'heureux / heureuse', 'nl-fr', 'Ik ben gelukkig.'),
('droevig', 'triste', 'nl-fr', 'Ze is droevig.'),
('boos', 'fâché / en colère', 'nl-fr', 'Hij is boos op mij.'),
('bang', 'peureux / effrayé', 'nl-fr', 'Ik ben bang voor spinnen.'),
('moe', 'fatigué', 'nl-fr', 'Ik ben moe na het werk.'),
('wakker', 'éveillé / réveillé', 'nl-fr', 'Ben je al wakker?'),
('gezond', 'en bonne santé / sain', 'nl-fr', 'Ik voel me gezond.'),
('slim', 'intelligent / malin', 'nl-fr', 'Ze is heel slim.'),
('grappig', 'drôle / amusant', 'nl-fr', 'Hij is heel grappig.'),
('rustig', 'calme', 'nl-fr', 'Het is rustig in het dorp.'),
('druk', 'occupé / animé', 'nl-fr', 'De stad is druk.'),
('vol', 'plein', 'nl-fr', 'De bus is vol.'),
('leeg', 'vide', 'nl-fr', 'Mijn glas is leeg.'),
('open', 'ouvert', 'nl-fr', 'De winkel is open.'),
('gesloten', 'fermé', 'nl-fr', 'De winkel is gesloten.'),
('hard', 'dur', 'nl-fr', 'De steen is hard.'),
('zacht', 'doux / mou', 'nl-fr', 'Het kussen is zacht.'),
('vrolijk', 'joyeux / gai', 'nl-fr', 'Ze is altijd vrolijk.'),
('verlegen', 'timide', 'nl-fr', 'Hij is een verlegen jongen.'),
('lief', 'gentil / mignon', 'nl-fr', 'Wat een lief kind.'),
('vriendelijk', 'aimable', 'nl-fr', 'De buren zijn vriendelijk.'),
('gevaarlijk', 'dangereux', 'nl-fr', 'Het is gevaarlijk om te rijden.'),
('veilig', 'sûr / en sécurité', 'nl-fr', 'Het is veilig hier.'),
('belangrijk', 'important', 'nl-fr', 'Dit is een belangrijk moment.'),
('mogelijk', 'possible', 'nl-fr', 'Is het mogelijk om te helpen?'),
('onmogelijk', 'impossible', 'nl-fr', 'Dat is onmogelijk.'),
('juist', 'correct / juste', 'nl-fr', 'Dat antwoord is juist.'),
('fout', 'faux / erroné', 'nl-fr', 'Dat is een fout antwoord.'),
('populair', 'populaire', 'nl-fr', 'Dit is een populair restaurant.'),
('speciaal', 'spécial', 'nl-fr', 'Dit is een speciale dag.'),
('normaal', 'normal', 'nl-fr', 'Dit is normaal gedrag.'),
('anders', 'différent / autrement', 'nl-fr', 'Dat is anders dan ik dacht.'),
('hetzelfde', 'le même / pareil', 'nl-fr', 'We hebben hetzelfde idee.'),
('lekker', 'délicieux / bon', 'nl-fr', 'Dit eten is heel lekker.'),

-- ADVERBES & EXPRESSIONS (30)
('hier', 'ici', 'nl-fr', 'Kom hier!'),
('daar', 'là / là-bas', 'nl-fr', 'De winkel is daar.'),
('nu', 'maintenant', 'nl-fr', 'Ik wil nu eten.'),
('later', 'plus tard', 'nl-fr', 'We praten later.'),
('altijd', 'toujours', 'nl-fr', 'Ik drink altijd koffie.'),
('nooit', 'jamais', 'nl-fr', 'Ik rook nooit.'),
('vaak', 'souvent', 'nl-fr', 'We gaan vaak naar het park.'),
('soms', 'parfois', 'nl-fr', 'Soms eet ik te veel.'),
('misschien', 'peut-être', 'nl-fr', 'Misschien kom ik morgen.'),
('graag', 'volontiers / avec plaisir', 'nl-fr', 'Ik drink graag koffie.'),
('heel', 'très', 'nl-fr', 'Ik ben heel moe.'),
('erg', 'très / beaucoup', 'nl-fr', 'Het is erg koud vandaag.'),
('bijna', 'presque', 'nl-fr', 'Ik ben er bijna.'),
('nog', 'encore', 'nl-fr', 'Wil je nog wat eten?'),
('al', 'déjà', 'nl-fr', 'Ben je al klaar?'),
('weer', 'encore / de nouveau', 'nl-fr', 'Hij is weer ziek.'),
('ook', 'aussi', 'nl-fr', 'Ik wil ook komen.'),
('alleen', 'seulement / seul', 'nl-fr', 'Ik woon alleen.'),
('samen', 'ensemble', 'nl-fr', 'We werken samen.'),
('thuis', 'à la maison', 'nl-fr', 'Ik blijf thuis.'),
('buiten', 'dehors', 'nl-fr', 'De kinderen spelen buiten.'),
('binnen', 'dedans / à l intérieur', 'nl-fr', 'Het is warm binnen.'),
('eindelijk', 'enfin / finalement', 'nl-fr', 'Eindelijk ben je hier!'),
('helaas', 'malheureusement / hélas', 'nl-fr', 'Helaas kan ik niet komen.'),
('gelukkig', 'heureusement', 'nl-fr', 'Gelukkig is alles goed.'),
('ongeveer', 'environ / à peu près', 'nl-fr', 'Het duurt ongeveer een uur.'),
('net', 'juste / à peine', 'nl-fr', 'Ik ben er net aangekomen.'),
('overal', 'partout', 'nl-fr', 'Ik zie bloemen overal.'),
('nergens', 'nulle part', 'nl-fr', 'Ik kan hem nergens vinden.'),
('morgen', 'demain', 'nl-fr', 'Morgen ga ik naar de markt.'),

-- PRÉPOSITIONS & CONJONCTIONS (20)
('in', 'dans / en', 'nl-fr', 'Ik woon in Amsterdam.'),
('op', 'sur / à', 'nl-fr', 'Het boek ligt op de tafel.'),
('aan', 'à / au bord de', 'nl-fr', 'Ze woont aan de zee.'),
('bij', 'chez / près de', 'nl-fr', 'Ik ben bij mijn vriend.'),
('voor', 'avant / pour / devant', 'nl-fr', 'Ik kom voor jou.'),
('na', 'après', 'nl-fr', 'We eten na de les.'),
('met', 'avec', 'nl-fr', 'Ik ga met mijn vriend.'),
('zonder', 'sans', 'nl-fr', 'Ik drink koffie zonder suiker.'),
('over', 'sur / à propos de', 'nl-fr', 'We praten over het werk.'),
('onder', 'sous / parmi', 'nl-fr', 'De kat zit onder de tafel.'),
('tussen', 'entre', 'nl-fr', 'De winkel is tussen de bank en het park.'),
('naar', 'vers / à', 'nl-fr', 'Ik ga naar school.'),
('van', 'de / d', 'nl-fr', 'Dit is de tas van mijn moeder.'),
('tot', 'jusqu à', 'nl-fr', 'Ik werk van negen tot vijf.'),
('en', 'et', 'nl-fr', 'Ik drink koffie en thee.'),
('maar', 'mais', 'nl-fr', 'Ik wil komen, maar ik kan niet.'),
('of', 'ou / si', 'nl-fr', 'Wil je koffie of thee?'),
('omdat', 'parce que', 'nl-fr', 'Ik leer Nederlands omdat ik in Nederland woon.'),
('als', 'si / quand / comme', 'nl-fr', 'Als het regent, blijf ik binnen.'),
('dus', 'donc', 'nl-fr', 'Het regent, dus ik neem een paraplu.'),

-- MOTS INTERROGATIFS & PRONOMS (18)
('wie', 'qui', 'nl-fr', 'Wie is dat?'),
('wat', 'quoi / que', 'nl-fr', 'Wat doe jij?'),
('waar', 'où', 'nl-fr', 'Waar woon jij?'),
('wanneer', 'quand', 'nl-fr', 'Wanneer kom jij?'),
('waarom', 'pourquoi', 'nl-fr', 'Waarom ben je moe?'),
('hoe', 'comment', 'nl-fr', 'Hoe gaat het?'),
('welk', 'quel / quelle', 'nl-fr', 'Welk boek kies jij?'),
('hoeveel', 'combien', 'nl-fr', 'Hoeveel kost dit?'),
('ik', 'je / moi', 'nl-fr', 'Ik heet Thomas.'),
('jij', 'tu / toi', 'nl-fr', 'Jij bent mijn vriend.'),
('hij', 'il / lui', 'nl-fr', 'Hij werkt in Amsterdam.'),
('zij', 'elle / elles / ils', 'nl-fr', 'Zij is heel slim.'),
('wij', 'nous', 'nl-fr', 'Wij gaan samen eten.'),
('jullie', 'vous', 'nl-fr', 'Jullie zijn welkom.'),
('mijn', 'mon / ma / mes', 'nl-fr', 'Dit is mijn huis.'),
('zijn', 'son / sa / ses', 'nl-fr', 'Dit is zijn tas.'),
('iedereen', 'tout le monde', 'nl-fr', 'Iedereen is welkom.'),
('niemand', 'personne', 'nl-fr', 'Niemand is thuis.'),

-- PROFESSIONS (30)
('arts', 'médecin', 'nl-fr', 'De arts onderzoekt de patiënt.'),
('tandarts', 'dentiste', 'nl-fr', 'Ik ga naar de tandarts voor een controle.'),
('apotheker', 'pharmacien', 'nl-fr', 'De apotheker geeft me medicijnen.'),
('professor', 'professeur d université', 'nl-fr', 'De professor geeft college.'),
('advocaat', 'avocat', 'nl-fr', 'Ik heb een advocaat nodig.'),
('rechter', 'juge', 'nl-fr', 'De rechter spreekt het vonnis uit.'),
('politieagent', 'policier', 'nl-fr', 'De politieagent helpt de mensen.'),
('brandweerman', 'pompier', 'nl-fr', 'De brandweerman blust het vuur.'),
('piloot', 'pilote', 'nl-fr', 'De piloot vliegt het vliegtuig.'),
('kok', 'cuisinier / chef', 'nl-fr', 'De kok maakt een heerlijk gerecht.'),
('kelner', 'serveur', 'nl-fr', 'De kelner brengt het eten.'),
('bakker', 'boulanger', 'nl-fr', 'De bakker maakt vers brood.'),
('slager', 'boucher', 'nl-fr', 'Ik koop vlees bij de slager.'),
('boer', 'agriculteur / fermier', 'nl-fr', 'De boer werkt op het land.'),
('architect', 'architecte', 'nl-fr', 'De architect ontwerpt het gebouw.'),
('ingenieur', 'ingénieur', 'nl-fr', 'De ingenieur bouwt de brug.'),
('journalist', 'journaliste', 'nl-fr', 'De journalist schrijft een artikel.'),
('fotograaf', 'photographe', 'nl-fr', 'De fotograaf maakt mooie foto s.'),
('acteur', 'acteur', 'nl-fr', 'De acteur speelt in een film.'),
('muzikant', 'musicien', 'nl-fr', 'De muzikant speelt gitaar.'),
('schilder', 'peintre', 'nl-fr', 'De schilder maakt een mooi schilderij.'),
('schrijver', 'écrivain', 'nl-fr', 'De schrijver heeft een boek geschreven.'),
('vertaler', 'traducteur', 'nl-fr', 'De vertaler vertaalt het boek.'),
('chauffeur', 'chauffeur', 'nl-fr', 'De chauffeur rijdt de bus.'),
('directeur', 'directeur', 'nl-fr', 'De directeur leidt het bedrijf.'),
('secretaresse', 'secrétaire', 'nl-fr', 'De secretaresse beheert de agenda.'),
('accountant', 'comptable', 'nl-fr', 'De accountant doet de boekhouding.'),
('psycholoog', 'psychologue', 'nl-fr', 'De psycholoog helpt mensen met problemen.'),
('verpleegster', 'infirmière', 'nl-fr', 'De verpleegster geeft medicijnen.'),
('steward', 'steward', 'nl-fr', 'De steward helpt de passagiers in het vliegtuig.'),

-- LIEUX & VILLE (30)
('stad', 'ville', 'nl-fr', 'Amsterdam is een grote stad.'),
('dorp', 'village', 'nl-fr', 'Ik woon in een rustig dorp.'),
('plein', 'place', 'nl-fr', 'Het plein is vol mensen.'),
('bioscoop', 'cinéma', 'nl-fr', 'We gaan naar de bioscoop.'),
('hotel', 'hôtel', 'nl-fr', 'We slapen in een hotel.'),
('camping', 'camping', 'nl-fr', 'We slapen op de camping.'),
('kerk', 'église', 'nl-fr', 'De kerk is heel oud.'),
('ambassade', 'ambassade', 'nl-fr', 'Ik ga naar de ambassade.'),
('speeltuin', 'aire de jeux', 'nl-fr', 'De kinderen spelen op de speeltuin.'),
('sportcentrum', 'centre sportif', 'nl-fr', 'Ik sport in het sportcentrum.'),
('winkelcentrum', 'centre commercial', 'nl-fr', 'We gaan naar het winkelcentrum.'),
('gemeentehuis', 'mairie / hôtel de ville', 'nl-fr', 'Ik ga naar het gemeentehuis.'),
('politiebureau', 'commissariat', 'nl-fr', 'Ik doe aangifte bij het politiebureau.'),
('postkantoor', 'bureau de poste', 'nl-fr', 'Ik stuur een pakket via het postkantoor.'),
('café', 'café', 'nl-fr', 'We drinken koffie in het café.'),
('bar', 'bar', 'nl-fr', 'We gaan naar de bar vanavond.'),
('buurt', 'quartier', 'nl-fr', 'Ik woon in een rustige buurt.'),
('centrum', 'centre-ville', 'nl-fr', 'We wandelen door het centrum.'),
('buitenland', 'étranger / à l étranger', 'nl-fr', 'Ik ga naar het buitenland.'),
('land', 'pays', 'nl-fr', 'Nederland is een mooi land.'),
('grens', 'frontière', 'nl-fr', 'We rijden over de grens.'),
('hoofdstad', 'capitale', 'nl-fr', 'Amsterdam is de hoofdstad van Nederland.'),
('kaart', 'carte / plan', 'nl-fr', 'Ik kijk op de kaart.'),
('richting', 'direction', 'nl-fr', 'In welke richting moeten we gaan?'),
('ingang', 'entrée', 'nl-fr', 'De ingang is aan de voorkant.'),
('uitgang', 'sortie', 'nl-fr', 'Waar is de uitgang?'),
('toilet', 'toilettes', 'nl-fr', 'Waar zijn de toiletten?'),
('lift', 'ascenseur', 'nl-fr', 'Neem de lift naar boven.'),
('trap', 'escalier', 'nl-fr', 'Ik neem de trap.'),
('parking', 'parking', 'nl-fr', 'Is er een parking in de buurt?'),

-- ÉMOTIONS & SENTIMENTS (22)
('liefde', 'amour', 'nl-fr', 'Liefde maakt gelukkig.'),
('vreugde', 'joie', 'nl-fr', 'Haar gezicht straalt van vreugde.'),
('verdriet', 'chagrin / tristesse', 'nl-fr', 'Ze huilt van verdriet.'),
('angst', 'peur / anxiété', 'nl-fr', 'Hij heeft angst voor de donker.'),
('boosheid', 'colère', 'nl-fr', 'Zijn boosheid is begrijpelijk.'),
('verrassing', 'surprise', 'nl-fr', 'Wat een verrassing!'),
('jaloezie', 'jalousie', 'nl-fr', 'Jaloezie is niet goed.'),
('trots', 'fierté', 'nl-fr', 'Ik ben trots op jou.'),
('hoop', 'espoir', 'nl-fr', 'Ik heb hoop voor de toekomst.'),
('teleurstelling', 'déception', 'nl-fr', 'De teleurstelling is groot.'),
('opluchting', 'soulagement', 'nl-fr', 'Wat een opluchting!'),
('enthousiasme', 'enthousiasme', 'nl-fr', 'Ze werkt met veel enthousiasme.'),
('eenzaamheid', 'solitude', 'nl-fr', 'Ze lijdt aan eenzaamheid.'),
('geluk', 'bonheur', 'nl-fr', 'Geluk is het mooiste in het leven.'),
('nerveus', 'nerveux', 'nl-fr', 'Ik ben nerveus voor het examen.'),
('ontspannen', 'détendu / relaxé', 'nl-fr', 'Na de vakantie voel ik me ontspannen.'),
('gevoel', 'sentiment / sensation', 'nl-fr', 'Ik heb een goed gevoel.'),
('emotie', 'émotion', 'nl-fr', 'Ik kan mijn emoties niet verbergen.'),
('bewondering', 'admiration', 'nl-fr', 'Ik heb bewondering voor hem.'),
('schaamte', 'honte', 'nl-fr', 'Ik voel schaamte.'),
('nostalgie', 'nostalgie', 'nl-fr', 'Ik voel nostalgie voor mijn jeugd.'),
('wanhoop', 'désespoir', 'nl-fr', 'Ze voelt wanhoop.'),

-- NOURRITURE NÉERLANDAISE (20)
('stroopwafel', 'gaufre au sirop', 'nl-fr', 'Een stroopwafel is heerlijk bij de koffie.'),
('drop', 'réglisse', 'nl-fr', 'Nederlandse drop is heel zoet of zout.'),
('poffertjes', 'petites crêpes hollandaises', 'nl-fr', 'Poffertjes met poedersuiker zijn lekker.'),
('bitterballen', 'croquettes de viande frites', 'nl-fr', 'Bitterballen zijn typisch Hollands.'),
('stamppot', 'purée de pommes de terre avec légumes', 'nl-fr', 'Stamppot met worst is lekker.'),
('erwtensoep', 'soupe aux pois cassés', 'nl-fr', 'Erwtensoep eet je in de winter.'),
('haring', 'hareng', 'nl-fr', 'Hollandse nieuwe haring is typisch.'),
('speculaas', 'spéculoos', 'nl-fr', 'Speculaas is een Sinterklaaskoekje.'),
('ontbijtkoek', 'pain d épices', 'nl-fr', 'Ontbijtkoek eet ik bij het ontbijt.'),
('vla', 'crème anglaise / flan', 'nl-fr', 'Ik eet vla als toetje.'),
('appelflap', 'chausson aux pommes', 'nl-fr', 'Een appelflap is lekker bij de koffie.'),
('kroket', 'croquette', 'nl-fr', 'Een broodje kroket is populair.'),
('frikandel', 'saucisse hollandaise', 'nl-fr', 'Een frikandel speciaal is populair.'),
('oliebollen', 'beignets hollandais', 'nl-fr', 'Met oud en nieuw eten we oliebollen.'),
('hagelslag', 'vermicelles en chocolat', 'nl-fr', 'Brood met hagelslag is typisch Nederlands.'),
('pindakaas', 'beurre de cacahuètes', 'nl-fr', 'Pindakaas op brood is lekker.'),
('rookworst', 'saucisse fumée', 'nl-fr', 'Rookworst eet ik in de stamppot.'),
('boerenkool', 'chou frisé / kale', 'nl-fr', 'Boerenkool stamppot is typisch winters.'),
('wentelteefjes', 'pain perdu', 'nl-fr', 'Wentelteefjes met poedersuiker zijn lekker.'),
('gevulde koek', 'biscuit fourré à la pâte d amande', 'nl-fr', 'Een gevulde koek is zoet en lekker.'),

-- MOTS ABSTRAITS & DIVERS (35)
('tijd', 'temps', 'nl-fr', 'We hebben geen tijd.'),
('ruimte', 'espace', 'nl-fr', 'Er is geen ruimte.'),
('energie', 'énergie', 'nl-fr', 'Ik heb geen energie vandaag.'),
('kracht', 'force', 'nl-fr', 'Hij heeft veel kracht.'),
('vrijheid', 'liberté', 'nl-fr', 'Vrijheid is een groot goed.'),
('vrede', 'paix', 'nl-fr', 'We willen vrede.'),
('probleem', 'problème', 'nl-fr', 'Ik heb een probleem.'),
('oplossing', 'solution', 'nl-fr', 'Ik zoek een oplossing.'),
('idee', 'idée', 'nl-fr', 'Ik heb een goed idee.'),
('plan', 'plan', 'nl-fr', 'We maken een plan.'),
('droom', 'rêve', 'nl-fr', 'Mijn droom is reizen.'),
('doel', 'but / objectif', 'nl-fr', 'Wat is jouw doel?'),
('succes', 'succès', 'nl-fr', 'Ik wens je veel succes.'),
('cultuur', 'culture', 'nl-fr', 'Ik ben geïnteresseerd in cultuur.'),
('traditie', 'tradition', 'nl-fr', 'Dit is een oude traditie.'),
('waarde', 'valeur', 'nl-fr', 'Familie heeft veel waarde voor mij.'),
('betekenis', 'signification / sens', 'nl-fr', 'Wat is de betekenis van dit woord?'),
('verhaal', 'histoire / récit', 'nl-fr', 'Hij vertelt een mooi verhaal.'),
('nieuws', 'nouvelles / actualités', 'nl-fr', 'Ik lees het nieuws elke dag.'),
('toekomst', 'avenir / futur', 'nl-fr', 'Ik maak me zorgen over de toekomst.'),
('verleden', 'passé', 'nl-fr', 'Het verleden kunnen we niet veranderen.'),
('bericht', 'message', 'nl-fr', 'Ik ontvang een bericht.'),
('vraag', 'question', 'nl-fr', 'Ik heb een vraag.'),
('antwoord', 'réponse', 'nl-fr', 'Wat is het antwoord?'),
('informatie', 'information', 'nl-fr', 'Ik zoek informatie.'),
('kans', 'chance / opportunité', 'nl-fr', 'Dit is een grote kans.'),
('ervaring', 'expérience', 'nl-fr', 'Ik heb veel ervaring.'),
('kennis', 'connaissance / savoir', 'nl-fr', 'Kennis is macht.'),
('mening', 'opinion / avis', 'nl-fr', 'Wat is jouw mening?'),
('reden', 'raison', 'nl-fr', 'Wat is de reden?'),
('gevolg', 'conséquence', 'nl-fr', 'Wat zijn de gevolgen?'),
('verschil', 'différence', 'nl-fr', 'Wat is het verschil?'),
('overeenkomst', 'ressemblance / accord', 'nl-fr', 'Er is een overeenkomst.'),
('regel', 'règle', 'nl-fr', 'Volg de regels.'),
('wet', 'loi', 'nl-fr', 'De wet is duidelijk.'),

-- SALUTATIONS & EXPRESSIONS QUOTIDIENNES (28)
('hallo', 'bonjour / salut', 'nl-fr', 'Hallo! Hoe gaat het?'),
('goedemorgen', 'bonjour (le matin)', 'nl-fr', 'Goedemorgen! Heb je goed geslapen?'),
('goedemiddag', 'bonjour (l après-midi)', 'nl-fr', 'Goedemiddag! Wat wilt u?'),
('goedenavond', 'bonsoir', 'nl-fr', 'Goedenavond! Welkom.'),
('goedenacht', 'bonne nuit', 'nl-fr', 'Goedenacht! Slaap lekker.'),
('dag', 'salut / au revoir', 'nl-fr', 'Dag! Tot morgen.'),
('tot ziens', 'au revoir', 'nl-fr', 'Tot ziens! Tot de volgende keer.'),
('tot morgen', 'à demain', 'nl-fr', 'Tot morgen, slaap lekker.'),
('alsjeblieft', 's il vous plaît / s il te plaît', 'nl-fr', 'Een koffie, alsjeblieft.'),
('dank je', 'merci', 'nl-fr', 'Dank je voor je hulp.'),
('dank u wel', 'merci beaucoup', 'nl-fr', 'Dank u wel voor uw tijd.'),
('graag gedaan', 'de rien / avec plaisir', 'nl-fr', 'Graag gedaan! Geen probleem.'),
('sorry', 'désolé / pardon', 'nl-fr', 'Sorry, ik ben te laat.'),
('excuseer', 'excusez-moi / pardon', 'nl-fr', 'Excuseer, waar is het toilet?'),
('ja', 'oui', 'nl-fr', 'Ja, ik kom morgen.'),
('nee', 'non', 'nl-fr', 'Nee, ik wil dat niet.'),
('hoe gaat het', 'comment allez-vous / ça va', 'nl-fr', 'Hoe gaat het met jou?'),
('goed', 'bien', 'nl-fr', 'Het gaat goed, dank je.'),
('niet zo goed', 'pas très bien', 'nl-fr', 'Het gaat niet zo goed vandaag.'),
('prima', 'parfait / très bien', 'nl-fr', 'Prima, geen probleem.'),
('gefeliciteerd', 'félicitations', 'nl-fr', 'Gefeliciteerd met je verjaardag!'),
('proficiat', 'félicitations', 'nl-fr', 'Proficiat met je diploma!'),
('veel succes', 'bonne chance', 'nl-fr', 'Veel succes met je examen!'),
('beterschap', 'bon rétablissement', 'nl-fr', 'Beterschap! Je bent snel beter.'),
('smakelijk', 'bon appétit', 'nl-fr', 'Smakelijk eten!'),
('proost', 'santé / tchin-tchin', 'nl-fr', 'Proost! Op ons succes.'),
('welkom', 'bienvenue', 'nl-fr', 'Welkom in Nederland!'),
('tot later', 'à tout à l heure', 'nl-fr', 'Tot later! Ik zie je snel.');
